"""
Per-template field manifests for the doctor-facing PDF editor.

Each manifest mirrors the shape the frontend FORM_SECTIONS already expects:
    { id, title, fields: [ { key, label, type? } ] }

`key` uses the same dotted-path convention as the frontend's
getNestedValue/setNestedValue (e.g. "hospitalDetails.name").
"""

COMMON_MEDIASSIST_MANIFEST = [
    {
        "id": "brief",
        "title": "Brief of the Case",
        "fields": [
            {"key": "referenceNumber", "label": "Ref No"},
            {"key": "reportDate", "label": "Report Date", "type": "date"},
            {"key": "claimantName", "label": "Name of Insured (Investigation)"},
            {"key": "briefInsured.patientName", "label": "Patient Name (As per Insured)"},
            {"key": "claimantAge", "label": "Age (Investigation)"},
            {"key": "briefInsured.dob", "label": "DOB / Age (As per Insured)"},
            {"key": "briefInvestigation.ageProof", "label": "Age Proof (Investigation)"},
            {"key": "briefInsured.ageProof", "label": "Age Proof (As per Insured)"},
            {"key": "briefInvestigation.occupation", "label": "Occupation (Investigation)"},
            {"key": "briefInsured.occupation", "label": "Occupation (As per Insured)"},
            {"key": "briefVerification.patientName", "label": "Patient Name Verified?", "type": "yn"},
            {"key": "briefVerification.dob", "label": "DOB Verified?", "type": "yn"},
            {"key": "briefVerification.ageProof", "label": "Age Proof Verified?", "type": "yn"},
            {"key": "briefVerification.occupation", "label": "Occupation Verified?", "type": "yn"},
            {"key": "briefComments.patientName", "label": "Comments — Patient Name", "type": "textarea"},
            {"key": "briefComments.dob", "label": "Comments — DOB", "type": "textarea"},
            {"key": "briefComments.ageProof", "label": "Comments — Age Proof", "type": "textarea"},
            {"key": "briefComments.occupation", "label": "Comments — Occupation", "type": "textarea"},
        ],
    },
    {
        "id": "policy",
        "title": "Policy Details",
        "fields": [
            {"key": "policyNumber", "label": "Policy No"},
            {"key": "policyDetails.holderName", "label": "Policy Holder Name"},
            {"key": "policyDetails.relation", "label": "Relation to Insured"},
            {"key": "policyType", "label": "Policy Type"},
        ],
    },
    {
        "id": "claim",
        "title": "Claim Details",
        "fields": [
            {"key": "hospitalDetails.admissionDate", "label": "Date/Time of Admission", "type": "date"},
            {"key": "hospitalDetails.dischargeDate", "label": "Date/Time of Discharge", "type": "date"},
            {"key": "cashlessDetails.icuDetails", "label": "ICU Admission Details"},
            {"key": "claimMode", "label": "Cashless / Non-Cashless"},
            {"key": "cashlessDetails.estimatedCost", "label": "Pre-Auth Estimated Cost"},
            {"key": "cashlessDetails.amountAuthorized", "label": "Amount Authorized"},
            {"key": "cashlessDetails.medicalHistory", "label": "Medical History (Pre-Auth)", "type": "textarea"},
            {"key": "criticalDetails.diagnosis", "label": "Diagnosis"},
            {"key": "additionalMedicalDetails.treatment", "label": "Treatment", "type": "textarea"},
            {"key": "hospitalDetails.name", "label": "Hospital Name"},
            {"key": "hospitalDetails.address", "label": "Hospital Address"},
            {"key": "hospitalDetails.registrationNumber", "label": "Registration Number"},
        ],
    },
    {
        "id": "ailment",
        "title": "Ailment Details",
        "fields": [
            {"key": "additionalMedicalDetails.onsetOfSymptoms", "label": "Onset of Symptoms"},
            {"key": "dateOfIncident", "label": "Date of First Onset (fallback)", "type": "date"},
            {"key": "additionalMedicalDetails.firstConsultation", "label": "First Consultation"},
            {"key": "familyDoctor", "label": "Referral Doctor (primary)"},
            {"key": "additionalMedicalDetails.referralDoctor", "label": "Referral Doctor (fallback)"},
            {"key": "additionalMedicalDetails.initialTreatment", "label": "Initial Treatment Details", "type": "textarea"},
            {"key": "additionalMedicalDetails.preHospitalisationDetails", "label": "Pre-Hospitalisation Details", "type": "textarea"},
            {"key": "additionalMedicalDetails.postHospitalisationDetails", "label": "Post-Hospitalisation Details", "type": "textarea"},
            {"key": "additionalMedicalDetails.investigationsSuggestingDiagnosis", "label": "Investigations for Diagnosis", "type": "textarea"},
            {"key": "investigationOutcome.outcome", "label": "Outcome"},
        ],
    },
    {
        "id": "checklist",
        "title": "Checklist (25-item)",
        "fields": [
            {"key": "checklist.inPatientVerification", "label": "1. In-patient verification", "type": "yn"},
            {"key": "checklist.idProofs", "label": "2. ID proofs", "type": "yn"},
            {"key": "checklist.ipdRecords", "label": "3. Copies of IPD records", "type": "yn"},
            {"key": "checklist.hospitalRegistered", "label": "4. Hospital registered", "type": "yn"},
            {"key": "checklist.mlcRegisterCheck", "label": "5. MLC register check", "type": "yn"},
            {"key": "checklist.mlcRegistrationCopy", "label": "6. Copy of MLC registration", "type": "yn"},
            {"key": "checklist.billsReceipts", "label": "7. Bills & receipts", "type": "yn"},
            {"key": "checklist.labVicinity", "label": "8. Lab vicinity", "type": "yn"},
            {"key": "checklist.labRegisterCheck", "label": "9. Lab register checked", "type": "yn"},
            {"key": "checklist.labRegisterPhotocopy", "label": "10. Lab register photocopy", "type": "yn"},
            {"key": "checklist.pharmacyVicinity", "label": "11. Pharmacy vicinity", "type": "yn"},
            {"key": "checklist.medicineReceipts", "label": "12. Medicine receipts", "type": "yn"},
            {"key": "checklist.receiptBookPhotocopy", "label": "13. Receipt book photocopy", "type": "yn"},
            {"key": "checklist.hospitalTests", "label": "14. Hospital tests", "type": "yn"},
            {"key": "checklist.diagnosticCentreTests", "label": "15. Diagnostic centre tests", "type": "yn"},
            {"key": "checklist.hospitalMedicines", "label": "16. Hospital-dispensed medicines", "type": "yn"},
            {"key": "checklist.pharmacyMedicines", "label": "17. Outside pharmacy medicines", "type": "yn"},
            {"key": "checklist.patientSignature", "label": "18. Patient signature", "type": "yn"},
            {"key": "checklist.otRegister", "label": "19. OT register copy", "type": "yn"},
            {"key": "checklist.hospitalLabRegister", "label": "20. Hospital lab register verified", "type": "yn"},
            {"key": "checklist.labRegisterCopy", "label": "21. Lab register copy", "type": "yn"},
            {"key": "checklist.hospitalBills", "label": "22. Hospital bills verified", "type": "yn"},
            {"key": "checklist.pharmacyBills", "label": "23. Pharmacy bills verified", "type": "yn"},
            {"key": "checklist.doctorCredentials", "label": "24. Doctor credentials", "type": "yn"},
            {"key": "checklist.signatureMatching", "label": "25. Signature matching", "type": "yn"},
        ],
    },
    {
        "id": "interview",
        "title": "Insured / Interview / Documents",
        "fields": [
            {"key": "claimantAddress", "label": "Insured's Address"},
            {"key": "interviewDetails.summary", "label": "Insured's Interview Summary", "type": "textarea"},
            {"key": "enclosures", "label": "List of Documents Collected", "type": "textarea"},
            {"key": "hospitalDetails.city", "label": "Place (Signature block)"},
        ],
    },
]

COMMON_INSURER_MANIFEST = [
    {
        "id": "claim",
        "title": "Claim Details",
        "fields": [
            {"key": "caseId", "label": "Claim ID"},
            {"key": "insurer", "label": "Company Name"},
            {"key": "claimantName", "label": "Insured Name"},
            {"key": "pre_extracted_facts.patient_age_gender", "label": "Age / Gender"},
            {"key": "claimMode", "label": "Type of Claim"},
            {"key": "pre_extracted_facts.accident_place", "label": "Insured Address (as extracted)"},
            {"key": "claimantMobile", "label": "Insured Contact Number"},
            {"key": "hospitalDetails.name", "label": "Hospital Name"},
            {"key": "hospitalDetails.address", "label": "Hospital Address"},
            {"key": "hospitalDetails.admissionDate", "label": "DOA", "type": "date"},
            {"key": "pre_extracted_facts.admission_time", "label": "Admission Time"},
            {"key": "hospitalDetails.dischargeDate", "label": "DOD", "type": "date"},
            {"key": "pre_extracted_facts.discharge_time", "label": "Discharge Time"},
            {"key": "pre_extracted_facts.final_diagnosis", "label": "Final Diagnosis"},
            {"key": "pre_extracted_facts.provisional_diagnosis", "label": "Provisional Diagnosis (fallback)"},
            {"key": "allocationDate", "label": "Allocation Date", "type": "date"},
            {"key": "reportingDate", "label": "Reporting Date", "type": "date"},
            {"key": "pre_extracted_facts.treatment_type", "label": "Treatment Type"},
            {"key": "policyNumber", "label": "Policy Number"},
            {"key": "policyInceptionDate", "label": "Policy Inception Date", "type": "date"},
            {"key": "claimTriggers", "label": "Trigger(s) — comma separated"},
        ],
    },
    {
        "id": "hospital_visit",
        "title": "Hospital Visit",
        "fields": [
            {"key": "pre_extracted_facts.field_officer_hospital_opinion", "label": "Hospital Visit Narrative", "type": "textarea"},
            {"key": "pre_extracted_facts.hospital_registration_number", "label": "Hospital Reg No"},
            {"key": "pre_extracted_facts.hospital_registration_validity", "label": "Reg Validity"},
            {"key": "pre_extracted_facts.hospital_bed_strength", "label": "Bed Strength"},
            {"key": "pre_extracted_facts.ip_register_collected", "label": "IP Register Collected", "type": "yn"},
            {"key": "pre_extracted_facts.inhouse_lab_present", "label": "In-house Lab Present", "type": "yn"},
            {"key": "pre_extracted_facts.hospital_criteria_fulfilled", "label": "Hospital Criteria Fulfilled", "type": "yn"},
            {"key": "pre_extracted_facts.nabh_certificate", "label": "NABH / Reg Certificate"},
            {"key": "pre_extracted_facts.hospital_cooperation", "label": "Hospital Cooperation", "type": "yn"},
            {"key": "billingDetails.totalBillAmount", "label": "Final Bill Amount"},
            {"key": "pre_extracted_facts.tariff", "label": "Tariff"},
            {"key": "pre_extracted_facts.treating_doctor", "label": "Treating Doctor Name"},
            {"key": "pre_extracted_facts.doctor_qualification", "label": "Doctor Qualification"},
            {"key": "pre_extracted_facts.doctor_reg_number", "label": "Doctor Reg Number"},
            {"key": "pre_extracted_facts.doctor_type", "label": "Doctor Type (Permanent/Visiting)"},
            {"key": "pre_extracted_facts.pathologist_name", "label": "Pathologist Name"},
            {"key": "pre_extracted_facts.radiology_details", "label": "Radiology Details"},
            {"key": "pre_extracted_facts.pharmacy_details", "label": "Pharmacy Details"},
            {"key": "pre_extracted_facts.market_feedback", "label": "Market Feedback", "type": "textarea"},
        ],
    },
    {
        "id": "member_findings",
        "title": "Member Findings",
        "fields": [
            {"key": "pre_extracted_facts.field_officer_member_opinion", "label": "Member Visit Narrative", "type": "textarea"},
            {"key": "pre_extracted_facts.physical_visit_confirmed", "label": "Physical Visit Confirmed", "type": "yn"},
            {"key": "pre_extracted_facts.chief_complaints", "label": "Chief Complaints", "type": "textarea"},
            {"key": "pre_extracted_facts.past_history", "label": "Past History", "type": "textarea"},
            {"key": "pre_extracted_facts.vicinity_check", "label": "Vicinity Check Done"},
            {"key": "pre_extracted_facts.mlc_registered", "label": "MLC Registered (RTA)", "type": "yn"},
            {"key": "pre_extracted_facts.mlc_number", "label": "MLC Number"},
            {"key": "pre_extracted_facts.accident_narration", "label": "Accident Narration", "type": "textarea"},
            {"key": "pre_extracted_facts.personal_habits", "label": "Personal Habits (Alcohol/Smoking/Tobacco)"},
            {"key": "pre_extracted_facts.birth_summary", "label": "Birth Summary (if child <10)"},
        ],
    },
    {
        "id": "investigation",
        "title": "Past Records / Investigation Findings",
        "fields": [
            {"key": "pre_extracted_facts.past_records", "label": "Past Records", "type": "textarea"},
            {"key": "pre_extracted_facts.discrepancies_verbatim", "label": "Discrepancies Found", "type": "textarea"},
            {"key": "pre_extracted_facts.contradictions_found", "label": "Contradictions Found (fallback)", "type": "textarea"},
        ],
    },
    {
        "id": "recommendation_agency",
        "title": "Recommendation & Agency Sign-off",
        "fields": [
            {"key": "pre_extracted_facts.recommendation", "label": "Recommendation", "type": "textarea"},
            {"key": "pre_extracted_facts.field_officer_name", "label": "FO Name"},
            {"key": "medicalStaff.fieldOfficer", "label": "FO Name (fallback)"},
            {"key": "pre_extracted_facts.qc_done_by", "label": "QC Done By"},
            {"key": "medicalStaff.qcOfficer", "label": "QC Officer (fallback)"},
            {"key": "pre_extracted_facts.report_prepared_by", "label": "Report Prepared By"},
            {"key": "medicalStaff.reportPreparedBy", "label": "Report Prepared By (fallback)"},
        ],
    },
]

NATIONAL_INSURANCE_MEDIASSIST_MANIFEST = [
    {
        "id": "policy",
        "title": "Policy Details",
        "fields": [
            {"key": "policyNumber", "label": "Policy Number"},
            {"key": "policyDetails.startDate", "label": "Policy Period — Start", "type": "date"},
            {"key": "policyDetails.endDate", "label": "Policy Period — End", "type": "date"},
            {"key": "insurerRef", "label": "Claim ID"},
            {"key": "policyDetails.sumInsured", "label": "Sum Insured"},
            {"key": "claimantName", "label": "Name of Insured"},
            {"key": "claimantAddress", "label": "Address / E-dress of Insured"},
            {"key": "claimantMobile", "label": "Contact Number of Insured"},
            {"key": "policyType", "label": "Type of Policy (NMP/Group/Individual/Floater etc.)"},
            {"key": "policyDetails.agentBroker", "label": "Agent / Broker on Record"},
            {"key": "policyDetails.inceptionDate", "label": "First Commencement Date", "type": "date"},
            {"key": "policyDetails.originalSumInsured", "label": "Original Sum Insured"},
            {"key": "policyDetails.sumInsuredEnhancement", "label": "Sum Insured Enhancement"},
            {"key": "policyDetails.policyYears", "label": "No. of Policy Years with Company"},
        ],
    },
    {
        "id": "brief",
        "title": "Patient Detail — Brief of the Case",
        "fields": [
            {"key": "claimantName", "label": "Patient Name (As per Investigation)"},
            {"key": "briefInsured.patientName", "label": "Patient Name (As per Insured)"},
            {"key": "claimantAge", "label": "Age (As per Investigation)"},
            {"key": "briefInsured.dob", "label": "DOB / Age (As per Insured)"},
            {"key": "briefInvestigation.ageProof", "label": "Age Proof (Investigation)"},
            {"key": "briefInsured.ageProof", "label": "Age Proof (As per Insured)"},
            {"key": "briefInvestigation.occupation", "label": "Occupation (Investigation)"},
            {"key": "briefInsured.occupation", "label": "Occupation (As per Insured)"},
            {"key": "briefVerification.patientName", "label": "Patient Name Verified?", "type": "yn"},
            {"key": "briefVerification.dob", "label": "DOB Verified?", "type": "yn"},
            {"key": "briefVerification.ageProof", "label": "Age Proof Verified?", "type": "yn"},
            {"key": "briefVerification.occupation", "label": "Occupation Verified?", "type": "yn"},
            {"key": "briefComments.patientName", "label": "Comments — Patient Name", "type": "textarea"},
            {"key": "briefComments.dob", "label": "Comments — DOB", "type": "textarea"},
            {"key": "briefComments.ageProof", "label": "Comments — Age Proof", "type": "textarea"},
            {"key": "briefComments.occupation", "label": "Comments — Occupation", "type": "textarea"},
        ],
    },
    {
        "id": "hospital",
        "title": "Hospital Detail",
        "fields": [
            {"key": "hospitalDetails.name", "label": "Hospital Name"},
            {"key": "hospitalDetails.address", "label": "Hospital Address / E-dress"},
            {"key": "hospitalDetails.registrationNumber", "label": "Hospital Registration Number"},
            {"key": "hospitalDetails.ppnStatus", "label": "PPN / Non-PPN"},
            {"key": "hospitalDetails.contactPerson", "label": "Contact Person"},
            {"key": "hospitalDetails.hospitalContactNumber", "label": "Hospital Contact Number"},
        ],
    },
    {
        "id": "claim",
        "title": "Claim & Ailment Details",
        "fields": [
            {"key": "claimMode", "label": "Cashless / Non-Cashless"},
            {"key": "hospitalDetails.admissionDate", "label": "Date/Time of Admission", "type": "date"},
            {"key": "hospitalDetails.dischargeDate", "label": "Date/Time of Discharge", "type": "date"},
            {"key": "cashlessDetails.icuDetails", "label": "ICU Admission Details"},
            {"key": "criticalDetails.diagnosis", "label": "Disease for which Admitted"},
            {"key": "cashlessDetails.estimatedCost", "label": "Estimated Treatment Cost (Hospital-submitted)"},
            {"key": "cashlessDetails.amountAuthorized", "label": "Amount Authorized"},
            {"key": "hospitalDetails.doctorName", "label": "Treating Doctor Name"},
            {"key": "hospitalDetails.doctorRegNumber", "label": "Treating Doctor Reg. Number"},
            {"key": "familyDoctor", "label": "Referral Doctor Name (primary)"},
            {"key": "additionalMedicalDetails.referralDoctor", "label": "Referral Doctor Name (fallback)"},
            {"key": "hospitalDetails.referralDoctorRegNumber", "label": "Referral Doctor Reg. Number"},
            {"key": "additionalMedicalDetails.initialTreatment", "label": "Initial Treatment Details", "type": "textarea"},
            {"key": "additionalMedicalDetails.onsetOfSymptoms", "label": "Date of First Onset of Symptoms"},
            {"key": "dateOfIncident", "label": "Date of First Onset (fallback)", "type": "date"},
            {"key": "additionalMedicalDetails.preHospitalisationDetails", "label": "Pre-Hospitalisation Details", "type": "textarea"},
            {"key": "additionalMedicalDetails.postHospitalisationDetails", "label": "Post-Hospitalisation Details", "type": "textarea"},
            {"key": "additionalMedicalDetails.investigationsSuggestingDiagnosis", "label": "Investigations for Diagnosis", "type": "textarea"},
        ],
    },
    {
        "id": "checklist",
        "title": "Checklist (12-item)",
        "fields": [
            {"key": "checklist.idProofInsured", "label": "1. ID proof of insured patient", "type": "yn"},
            {"key": "checklist.hospitalExistence", "label": "2. Hospital existence & registration", "type": "yn"},
            {"key": "checklist.admissionVerified", "label": "3. Admission of patient on stated dates", "type": "yn"},
            {"key": "checklist.treatmentParticulars", "label": "4. Treatment particulars", "type": "yn"},
            {"key": "checklist.copyOfICP", "label": "5. Copy of ICP", "type": "yn"},
            {"key": "checklist.labVicinity", "label": "6. Lab in vicinity / far off", "type": "yn"},
            {"key": "checklist.labRegistersVerified", "label": "7. Lab registers verified", "type": "yn"},
            {"key": "checklist.billsReceipts", "label": "8. Bills & receipts verified", "type": "yn"},
            {"key": "checklist.medicinePurchases", "label": "9. Medicine shop purchases", "type": "yn"},
            {"key": "checklist.signatureMatching", "label": "10. Signature matching", "type": "yn"},
            {"key": "checklist.otReceiptBooks", "label": "11. OT / receipt book copies", "type": "yn"},
            {"key": "checklist.anyOther", "label": "12. Any other", "type": "yn"},
        ],
    },
    {
        "id": "interview",
        "title": "Interview Detail / Documents",
        "fields": [
            {"key": "interviewDetails.neighbours", "label": "Neighbours", "type": "textarea"},
            {"key": "enclosures", "label": "List of Documents Collected", "type": "textarea"},
        ],
    },
    {
        "id": "meta",
        "title": "Report Meta",
        "fields": [
            {"key": "reportDate", "label": "Report Date", "type": "date"},
            {"key": "hospitalDetails.city", "label": "Place (Signature block)"},
        ],
    },
]

# Maps the *template filename* (as returned by resolve_template) to its manifest.
# Templates without an entry here fall back to the frontend's generic FORM_SECTIONS.
TEMPLATE_MANIFEST_MAP = {
    "common_mediassist.html": COMMON_MEDIASSIST_MANIFEST,
    "common_insurer.html": COMMON_INSURER_MANIFEST,
    "national_insurance_mediassist.html": NATIONAL_INSURANCE_MEDIASSIST_MANIFEST,
}


def get_manifest_for_template(template_filename: str):
    """Returns the field manifest for a template, or None if not yet mapped."""
    return TEMPLATE_MANIFEST_MAP.get(template_filename)