const labels = {
  v2_ckd_diag_date: "date of ckd diagnosis",
  v2_rrt_start_date: "dialysis initiation date",
  v2_ckd_vac_hepb: "hepatitis B vaccination", v2_ckd_vac_pneumo: "pneumococcal vaccination", v2_ckd_vac_flu: "influenza vaccination", v2_ckd_vac_covid: "COVID vaccination",
  v2_access_qa_measure: "access flow",
  v2_access_recirc_measure: "recirculation",
  v2_access_ready: "readiness status",
  v2_access_doppler_surv: "quarterly doppler ultrasound surveillance",
  v2_access_monthly_exam: "monthly physical exam findings",
  v2_hd_qb: "blood flow rate qb",
  v2_hd_qd: "dialysate flow rate qd",
  v2_hd_dialyzer: "dialyzer membrane",
  v2_hd_duration: "session duration",
  v2_hd_freq: "dialysis frequency",
  v2_hd_pre_weight: "pre-dialysis weight",
  v2_hd_dry_weight: "target dry weight",
  v2_hd_uf_goal: "uf goal liters",
  v2_hd_uf_rate: "uf rate ml/kg/hr",
  v2_hd_vitals_feed: "vital signs feed",
  v2_hd_active_alerts: "active alerts",
  v2_hd_interventions: "nurse interventions",
  v2_hd_vol_exam: "euvolemia exam",
  v2_hd_dw_adj: "dry weight adjustment",
  v2_hd_bis: "bioimpedance spectroscopy",
  v2_hd_ivc: "ivc diameter",
  v2_hd_ktv: "kt/v adequacy",
  v2_hd_urr: "urea reduction ratio urr",
  v2_hd_adequacy_adj: "adequacy adjustment strategy",
  v2_hd_bath_na: "dialysate sodium",
  v2_hd_bath_k: "dialysate potassium",
  v2_hd_bath_ca: "dialysate calcium",
  v2_hd_bath_bicarb: "bicarbonate supplementation",
  v2_pd_modality: "pd modality",
  v2_pd_exchanges: "exchanges per day",
  v2_pd_volume: "exchange volume liters",
  v2_pd_dwell: "dwell time hours",
  v2_pd_dextrose: "dialysate glucose concentration",
  v2_pd_home_uf: "daily uf volume tracking ml",
  v2_pd_uf_fail: "uf failure detection",
  v2_pd_ktv: "weekly kt/v",
  v2_pd_rrf: "residual renal function",
  v2_pd_pet: "membrane transport type",
  v2_pd_pet_adj: "prescription adjustment per pet",
  v2_pd_peritonitis_symp: "symptom checklist",
  v2_pd_wbc: "effluent wbc",
  v2_pd_pmn: "percent pmns",
  v2_pd_culture: "gram stain culture results",
  v2_pd_abx: "antibiotic protocol",
  v2_pd_recurrence: "recurrence tracking",
  v2_pd_cath_remove: "catheter removal indicated",
  v2_home_rpm_sync: "bluetooth vitals sync",
  v2_home_machine_sync: "machine cloud upload",
  v2_home_rpm_alerts: "rule based alerts",
  v2_home_rpm_triage: "triage level status",
  v2_home_hd_sessions: "session completion vs scheduled",
  v2_home_hd_alarms: "machine alarms adequacy",
  v2_home_pd_log: "patient logged daily uf",
  v2_home_pd_photos: "photo uploads",
  v2_rrt_ktv: "monthly single pool kt/v",
  v2_rrt_urr: "urea reduction ratio",
  v2_rrt_residual_vol: "24h urine volume ml",
  v2_rrt_residual_clearance: "residual urea clearance",
  v2_rrt_dry_weight: "current target dry weight",
  v2_rrt_idwg: "avg interdialytic weight gain",
  v2_rrt_fluid_status: "clinical fluid status",
  v2_rrt_dry_weight_action: "dry weight action",
  v2_rrt_access_dvp: "dynamic venous pressure",
  v2_rrt_access_qa: "access flow rate",
  v2_rrt_access_exam: "physical exam thrill bruit",
  v2_rrt_access_action: "intervention recommended",
  v2_rrt_comp_hypotension: "recurrent intradialytic hypotension",
  v2_rrt_comp_cramps: "severe cramping events",
  v2_rrt_comp_notes: "notes protocol changes",
};
const keys = `v2_ckd_diag_date v2_rrt_start_date v2_ckd_vac_hepb v2_ckd_vac_pneumo v2_ckd_vac_flu v2_ckd_vac_covid v2_risk_kdigo_g v2_risk_kdigo_a v2_risk_category v2_risk_percentile v2_risk_modifiable v2_risk_nonmodifiable v2_risk_sim_action v2_risk_sim_result v2_risk_care_visits v2_risk_care_labs v2_risk_care_referral_target v2_risk_care_referral_status v2_rrt_vein_mapping v2_rrt_surg_consult v2_rrt_education v2_rrt_tx_workup v2_rrt_egfr_trigger v2_rrt_ed_session v2_rrt_ed_content v2_rrt_ed_aids v2_rrt_pref_survey v2_rrt_suitability v2_rrt_final_choice v2_rrt_tx_referral v2_rrt_tx_check v2_rrt_tx_donor_ed v2_rrt_tx_waitlist v2_risk_ai_accel v2_risk_ai_subgroup v2_risk_ai_shap v2_risk_ai_validation v2_bp_office v2_bp_home v2_bp_target v2_bp_alert v2_raas_indicated v2_raas_contra v2_raas_current_dose v2_raas_target_dose v2_raas_fu_ordered v2_raas_hold v2_k_level v2_k_alert v2_k_med_adj v2_k_diet v2_k_binder v2_k_recheck v2_dm_hba1c v2_dm_retinopathy v2_dm_neuropathy v2_sglt2_elig v2_sglt2_contra v2_sglt2_drug v2_sglt2_ed v2_sglt2_monitor v2_sglt2_response v2_mra_elig v2_mra_k_risk v2_mra_dose v2_mra_monitor v2_mra_hold v2_mra_triple v2_diet_na v2_diet_protein v2_diet_k v2_diet_phos v2_diet_referral v2_dm_target v2_dm_med_safety v2_dm_glp1 v2_dm_hypo_risk v2_lipid_ldl v2_lipid_hdl v2_lipid_tg v2_lipid_ascvd v2_lipid_statin v2_lipid_statin_monitor v2_lifestyle_bmi v2_lifestyle_weight_goal v2_lifestyle_referral v2_smoke_status v2_smoke_plan v2_anemia_hb v2_anemia_ferritin v2_anemia_tsat v2_anemia_workup v2_iron_crit v2_iron_route v2_iron_order v2_iron_monitor v2_iron_overload v2_esa_ind v2_esa_contra v2_esa_drug v2_esa_target v2_esa_hypo v2_ai_esa_dose v2_ai_esa_hypo_risk v2_ai_iron_absorp v2_ai_anemia_risk v2_mbd_ca v2_mbd_po4 v2_mbd_pth v2_mbd_alk v2_mbd_vitd_25 v2_mbd_vitd_125 v2_mbd_bone_turnover v2_mbd_binder_ind v2_mbd_binder_drug v2_mbd_binder_dose v2_mbd_calc_load v2_mbd_binder_monitor v2_mbd_active_vitd_ind v2_mbd_active_vitd_drug v2_mbd_active_vitd_dose v2_mbd_hyperca_hold v2_mbd_calcimimetic_ind v2_mbd_calcimimetic_drug v2_mbd_calcimimetic_monitor v2_mbd_calcimimetic_se v2_mbd_nutr_vitd_ind v2_mbd_nutr_vitd_drug v2_mbd_nutr_vitd_phase v2_ai_mbd_pth_trend v2_ai_mbd_binder_rec v2_ai_mbd_vitd_dose v2_ai_mbd_fracture_risk v2_elec_na v2_elec_na_analysis v2_elec_k v2_elec_k_analysis v2_elec_hco3 v2_elec_acidbase_interp v2_fluid_in v2_fluid_out v2_fluid_net v2_fluid_clinical v2_fluid_ai_flag v2_access_egfr_trig v2_access_target v2_access_mapping v2_access_doppler v2_access_map_result v2_access_referral v2_access_pref v2_access_coord v2_access_type v2_access_date v2_access_pe v2_access_6wk_us v2_access_ready v2_access_cvc v2_access_cvc_comp v2_access_cvc_remove v2_access_monthly_exam v2_access_aneurysm_inf v2_access_qa_measure v2_access_recirc_measure v2_access_vp_ratio v2_access_doppler_surv v2_access_stenosis_diag v2_access_ir_ref v2_access_procedure_done v2_access_post_ir_flow v2_access_lock_proto v2_access_tpa_use v2_access_exit_care v2_access_crbsi_track v2_hd_qb v2_hd_qd v2_hd_dialyzer v2_hd_duration v2_hd_freq v2_hd_pre_weight v2_hd_dry_weight v2_hd_uf_goal v2_hd_uf_rate v2_hd_vitals_feed v2_hd_active_alerts v2_hd_interventions v2_hd_vol_exam v2_hd_dw_adj v2_hd_bis v2_hd_ivc v2_hd_ktv v2_hd_urr v2_hd_adequacy_adj v2_hd_bath_na v2_hd_bath_k v2_hd_bath_ca v2_hd_bath_bicarb v2_pd_modality v2_pd_exchanges v2_pd_volume v2_pd_dwell v2_pd_dextrose v2_pd_home_uf v2_pd_uf_fail v2_pd_ktv v2_pd_rrf v2_pd_pet v2_pd_pet_adj v2_pd_peritonitis_symp v2_pd_wbc v2_pd_pmn v2_pd_culture v2_pd_abx v2_pd_recurrence v2_pd_cath_remove v2_home_rpm_sync v2_home_machine_sync v2_home_rpm_alerts v2_home_rpm_triage v2_home_hd_sessions v2_home_hd_alarms v2_home_pd_log v2_home_pd_photos v2_rrt_ktv v2_rrt_urr v2_rrt_residual_vol v2_rrt_residual_clearance v2_rrt_dry_weight v2_rrt_idwg v2_rrt_fluid_status v2_rrt_dry_weight_action v2_rrt_access_dvp v2_rrt_access_qa v2_rrt_access_exam v2_rrt_access_action v2_rrt_comp_hypotension v2_rrt_comp_cramps v2_rrt_comp_notes`.split(" ");
const vaccineOptions = {
  v2_ckd_vac_hepb: ["Immune (Checked Titer)", "Series Completed", "Series In Progress", "Not Started / Need to Order"],
  v2_ckd_vac_pneumo: ["Up to Date", "Needs PCV", "Needs PPSV23", "Unknown/Declined"],
  v2_ckd_vac_flu: ["Completed this season", "Needs ordering", "Declined"],
  v2_ckd_vac_covid: ["Up to Date", "Due for Booster", "Declined"],
  v2_risk_kdigo_g: ["G1 (Normal/High >=90)", "G2 (Mild 60-89)", "G3a (Mild-Mod 45-59)", "G3b (Mod-Severe 30-44)", "G4 (Severe 15-29)", "G5 (Failure <15)"],
  v2_risk_kdigo_a: ["A1 (Normal/Mild <30)", "A2 (Moderate 30-300)", "A3 (Severe >300)"],
  v2_risk_category: ["Low", "Medium", "High", "Very High"],
  v2_risk_sim_action: ["Strict BP Control (<120/80)", "SGLT2 Inhibitor Initiation", "10% Weight Loss", "Combined Intervention"],
  v2_risk_care_visits: ["Annual", "Every 6 months", "Every 3 months", "Monthly"],
  v2_risk_care_labs: ["Routine (Annual)", "Moderate (Bi-annual)", "Intensive (Quarterly)"],
  v2_risk_care_referral_target: ["None", "Cardiology (High CV Risk)", "Dietician (Hyperkalemia/CKD Diet)", "Urology (Obstruction)"],
  v2_risk_care_referral_status: ["Draft / Ordered", "Sent", "Scheduled", "Seen by Specialist", "Notes Received (Closed Loop)"],
  v2_rrt_vein_mapping: ["Ordered", "Completed - Suitable", "Completed - Unsuitable"],
  v2_rrt_surg_consult: ["Pending", "Scheduled", "Seen", "AVF Created", "AVG Created"],
  v2_rrt_education: ["Referred", "Completed - Chose HD", "Completed - Chose PD", "Completed - Conservative Care"],
  v2_rrt_tx_workup: ["Not Indicated/Contraindicated", "Referred to Center", "Evaluation in Progress", "Active on Waitlist"],
  v2_rrt_egfr_trigger: ["Triggered (eGFR <20)", "Not Triggered"],
  v2_rrt_ed_session: ["Scheduled", "Completed", "Patient Declined"],
  v2_rrt_ed_content: ["Yes (HD, PD, Transplant, Conservative)", "Pending"],
  v2_rrt_ed_aids: ["Yes", "No"],
  v2_rrt_pref_survey: ["Completed - Prefers Home", "Completed - Prefers In-Center", "Completed - Prefers Conservative", "Pending"],
  v2_rrt_suitability: ["All Modalities Suitable", "PD Contraindicated (Prior Abd Surgery/Dexterity)", "Home HD Contraindicated (Housing/Partner)", "Transplant Contraindicated"],
  v2_rrt_final_choice: ["In-Center HD", "Home HD", "Peritoneal Dialysis", "Pre-emptive Transplant", "Conservative Management"],
  v2_rrt_tx_referral: ["Sent", "Pending", "Not Indicated"],
  v2_rrt_tx_check: ["Cleared (Cardiac/Malignancy/ID/Psych)", "Pending Workup", "Contraindication Found"],
  v2_rrt_tx_donor_ed: ["Yes", "No", "N/A"],
  v2_rrt_tx_waitlist: ["Active", "Inactive/Hold", "Not Listed"],
  v2_access_egfr_trig: ["eGFR <20: Initiate Discussion", "eGFR <15: Surgical Referral", "Not Triggered"],
  v2_access_target: ["On Track (Access ready before HD)", "Delayed (At risk for CVC)"],
  v2_access_mapping: ["Pending", "Scheduled", "Completed"],
  v2_access_doppler: ["N/A", "Pending", "Completed"],
  v2_access_referral: ["Generated", "Sent", "Pending"],
  v2_access_coord: ["Appointment Scheduled", "Waiting List", "Follow-up Needed"],
  v2_access_type: ["None", "AV Fistula (AVF)", "AV Graft (AVG)", "Tunneled CVC", "Temporary CVC", "PD Catheter"],
  v2_access_6wk_us: ["Pending", "Mature (Flow >500, Dia >4mm, Depth <6mm)", "Immature / Failed"],
  v2_access_ready: ["Not Ready", "Ready for Dialysis Initiation"],
  v2_access_cvc: ["Yes (Bridging to AVF/AVG)", "Yes (Permanent)", "No"],
  v2_access_cvc_comp: ["None", "Infection (CRBSI)", "Thrombosis", "Malfunction / Poor Flow"],
  v2_access_cvc_remove: ["N/A", "Pending AVF Maturation", "Scheduled for Removal", "Removed"],
  v2_access_monthly_exam: ["Normal", "Abnormal (Weak thrill / High-pitch bruit)", "Difficulty Cannulating", "Prolonged Bleeding", "Arm Swelling"],
  v2_access_doppler_surv: ["Normal", "Diagnostic for Stenosis"],
  v2_access_stenosis_diag: ["None", ">50% Diameter Reduction", "Peak Systolic Velocity >400 cm/s", "Flow <500 mL/min"],
  v2_access_ir_ref: ["None", "Interventional Nephrology", "Vascular Surgery"],
  v2_access_procedure_done: ["Angioplasty (Balloon +/- Stent)", "Surgical Revision", "Thrombectomy"],
  v2_access_lock_proto: ["Heparin Lock", "Citrate Lock"],
  v2_access_tpa_use: ["Normal Flow", "Poor Flow - tPA Administered"],
  v2_access_exit_care: ["Clean / Intact", "Erythema / Discharge"],
  v2_access_crbsi_track: ["No Infection", "Suspected", "Confirmed CRBSI"],
  v2_hd_dialyzer: ["Standard High-Flux", "Large High-Flux", "Medium High-Flux"],
  v2_hd_freq: ["3x per week", "2x per week", "4x per week", "Daily"],
  v2_hd_active_alerts: ["None", "Hypotension", "Tachycardia", "Machine Alarm (Air/Leak)"],
  v2_hd_interventions: ["None", "Saline Bolus Given", "UF Rate Adjusted/Paused", "Trendelenburg Position", "Oxygen Administered"],
  v2_hd_vol_exam: ["Euvolemic", "Overloaded", "Depleted"],
  v2_hd_dw_adj: ["No Change", "Decrease by 0.2-0.5 kg", "Increase by 0.2-0.5 kg"],
  v2_hd_ivc: ["Not Done", "Plethoric", "Collapsible"],
  v2_hd_adequacy_adj: ["N/A - Adequate", "Increase QB", "Increase QD", "Increase Time", "Larger Dialyzer"],
  v2_hd_bath_k: ["1K", "2K", "3K", "4K"],
  v2_hd_bath_ca: ["2.0", "2.25", "2.5", "3.0"],
  v2_pd_modality: ["CAPD (Continuous Ambulatory)", "APD (Automated Cycler)"],
  v2_pd_dextrose: ["1.5%", "2.5%", "4.25%", "Mixed/Icodextrin"],
  v2_pd_uf_fail: ["Adequate UF", "Low UF (Membrane Failure)", "Low UF (Catheter Malposition)", "Low UF (Peritoneal Sclerosis)"],
  v2_pd_pet: ["High Transport", "High-Average Transport", "Low-Average Transport", "Low Transport"],
  v2_pd_peritonitis_symp: ["None", "Cloudy Effluent", "Abdominal Pain", "Fever", "Multiple Symptoms"],
  v2_pd_abx: ["Empiric (Cefazolin + Ceftazidime IP)", "Targeted per Culture", "Completed Course"],
  v2_pd_recurrence: ["First Episode", "Relapsing", "Recurrent", "Repeat"],
  v2_pd_cath_remove: ["No", "Yes (Refractory/Fungal/Relapsing)"],
  v2_home_rpm_sync: ["Synced Today", "Sync Delayed", "Offline"],
  v2_home_machine_sync: ["Session Data Uploaded", "Pending Upload", "Error"],
  v2_home_rpm_triage: ["Green (Routine Next Visit)", "Yellow (Nurse Call <24h)", "Red (Urgent Call/ED Referral)"],
  v2_home_hd_sessions: ["100% Adherence", "Missed Session", "Shortened Session"],
  v2_home_pd_photos: ["Clear / Normal", "AI Flagged Turbidity/Redness", "Missing", "Not Required Today"],
  v2_rrt_fluid_status: ["Euvolemic (At dry weight)", "Hypervolemic (Edema/SOB)", "Hypovolemic (Cramping/Hypotension)"],
  v2_rrt_dry_weight_action: ["Maintain current target", "Decrease target (Challenge)", "Increase target"],
  v2_rrt_access_exam: ["Normal (Continuous thrill/bruit)", "Abnormal (Pulsatile thrill/high pitch bruit)", "Loss of thrill/bruit (Thrombosis)"],
  v2_rrt_access_action: ["None (Monitor)", "Refer for Fistulagram/Angioplasty", "Refer for Surgical Revision"],
  v2_rrt_comp_hypotension: ["None", "Rare (<10% of sessions)", "Frequent (>30% of sessions)"],
  v2_rrt_comp_cramps: ["None", "Occasional", "Frequent/Severe"],
};

export const CKD_DICTATION_FIELDS = keys.map((k) => {
  const isNumber = /(^|_)(level|hb|ferritin|tsat|hba1c|ldl|hdl|tg|ca|po4|pth|alk|vitd|na|k|in|out|net|percentile|measure|qb|qd|duration|weight|goal|rate|ktv|urr|bicarb|exchanges|volume|dwell|uf|wbc|pmn|vol|clearance|idwg|dvp|qa)$/.test(k);
  const isDate = /(date)$/.test(k);
  const options = vaccineOptions[k];
  return {
    k,
    label: labels[k] || k.replace(/^v2_/, "").replaceAll("_", " "),
    type: options ? "select" : isNumber ? "number" : isDate ? "date" : "text",
    ...(options ? { options } : {}),
  };
});
export const CKD_HISTORY_KEYS = keys;
export const ckdFieldsFor = (...prefixes) => CKD_DICTATION_FIELDS.filter(({ k }) => prefixes.some((prefix) => k.startsWith(prefix)));
