export const TX_DICTATION_FIELDS = [
  { k: "v2_tx_eval_date", label: "transplant evaluation date", type: "date" },
  { k: "v2_tx_med_fit", label: "medical fitness age", options: ["Suitable", "Borderline/High Risk", "Contraindicated"] },
  { k: "v2_tx_psych_comp", label: "psychosocial stability compliance", options: ["Cleared by Social Work", "Pending Evaluation", "Concerns Noted"] },
  { k: "v2_tx_excl_malig", label: "active malignancy or infection", options: ["None", "Active Issue Identified"] },
  { k: "v2_tx_excl_cardiac", label: "severe cardiac disease substance abuse", options: ["None", "Active Issue Identified"] },
  { k: "v2_tx_clear_cardio", label: "cardiovascular stress echo ekg", options: ["Pending", "Cleared", "Needs Intervention"] },
  { k: "v2_tx_clear_id", label: "infectious disease hiv hcv cmv tb", options: ["Pending", "Cleared", "Treatment Required"] },
  { k: "v2_tx_clear_malig", label: "malignancy screening colon mammogram", options: ["Pending", "Cleared", "Follow-up Needed"] },
  { k: "v2_tx_clear_immuno", label: "immunology abo hla pra", options: ["Pending", "Completed"] },
  { k: "v2_tx_clear_dental", label: "dental clearance", options: ["Pending", "Cleared", "Procedures Needed"] },
  { k: "v2_tx_overdue_tests", label: "overdue tests reminders", options: undefined },
  
  // Donor Eligibility & Waitlist
  { k: "v2_tx_donors_list", label: "list of potential donors (extract as JSON array of objects with keys: name, relation, bloodType, hla)", options: undefined },
  { k: "v2_tx_donor_status", label: "donor workup status", options: ["Initial Screening", "Medical/Psych Clearance Pending", "Cleared for Surgery", "Ruled Out"] },
  { k: "v2_tx_donor_compat", label: "compatibility abo hla crossmatch", options: ["Pending", "Compatible", "Incompatible (Needs Desensitization/Paired Exchange)"] },
  { k: "v2_tx_donor_kdri", label: "donor risk assessment kdri prediction", options: undefined },
  { k: "v2_tx_unos_status", label: "unos registration status", options: ["Not Listed", "Active (Status 1)", "Inactive/Hold (Status 7)"] },
  { k: "v2_tx_unos_time", label: "waitlist start date", options: undefined },
  { k: "v2_tx_cpra", label: "cpra calculated pra", options: undefined },
  { k: "v2_tx_desens_proto", label: "active protocol plasmapheresis ivig rituximab", options: ["N/A", "Initiated", "Completed", "Failed"] },
  { k: "v2_tx_dsa_monitor", label: "donor specific antibody dsa monitoring", options: undefined },

  // Immunosuppression & Toxicity
  { k: "v2_tx_induction", label: "induction regimen used", options: ["Thymoglobulin", "Basiliximab", "Alemtuzumab", "None"] },
  { k: "v2_tx_maintenance", label: "current maintenance regimen", options: undefined },
  { k: "v2_tx_tac_trough", label: "tacrolimus trough", options: undefined },
  { k: "v2_tx_tac_target", label: "target tacrolimus range", options: ["4-6", "5-8", "8-10"] },
  { k: "v2_tx_cyclo_trough", label: "cyclosporine sirolimus level", options: undefined },
  { k: "v2_tx_dose_ai", label: "dose adjustment intelligence", options: ["In Range - Continue Current Dose", "Subtherapeutic - Increase Dose", "Supratherapeutic - Decrease Dose"] },
  { k: "v2_tx_tox_cni", label: "cni nephrotoxicity suspected", options: ["Yes", "No"] },
  { k: "v2_tx_tox_nodat", label: "new onset diabetes after transplant nodat", options: ["Yes", "No"] },
  { k: "v2_tx_tox_myelo", label: "leukopenia myelosuppression", options: ["Yes", "No"] },
  
  // Post-Transplant Surveillance
  { k: "v2_tx_surgery_date", label: "transplant surgery date", type: "date" },
  { k: "v2_post_cr", label: "current serum creatinine", options: undefined },
  { k: "v2_post_egfr", label: "current egfr", options: undefined },
  { k: "v2_post_base_cr", label: "baseline creatinine established", options: ["Yes", "Pending (First 3 months)"] },
  { k: "v2_post_dgf", label: "graft function classification", options: ["Immediate Graft Function", "Delayed Graft Function (DGF)", "Slow Graft Function"] },
  { k: "v2_post_phase", label: "monitoring phase", options: ["Intensive (<3 months)", "Intermediate (3-6 months)", "Long-term Maintenance"] },
  { k: "v2_post_urine", label: "urine uacr & microscopy", options: undefined },
  { k: "v2_post_proto_bx", label: "protocol biopsy status", options: ["Not Indicated", "Pending", "Completed"] },
  { k: "v2_post_cni", label: "calcineurin inhibitor cni", options: ["Tacrolimus", "Cyclosporine", "None"] },
  { k: "v2_post_cni_level", label: "cni trough level", options: undefined },
  { k: "v2_post_antimetab", label: "antimetabolite", options: ["Mycophenolate", "Azathioprine", "None"] },
  { k: "v2_post_steroid", label: "steroid maintenance", options: ["Prednisone Active", "Steroid Avoidance/Withdrawal"] },
  { k: "v2_post_toxicity", label: "drug interactions toxicity", options: undefined },
  { k: "v2_post_nodat", label: "new onset diabetes after transplant nodat", options: ["Negative", "Screening Due", "Positive"] },
  { k: "v2_post_ae_other", label: "other effects tremor gi", options: undefined },
  { k: "v2_post_inf_cmv", label: "cmv dna pcr", options: undefined },
  { k: "v2_post_inf_bkv", label: "bk virus bkv pcr", options: undefined },
  { k: "v2_post_inf_proph", label: "active prophylaxis", options: ["Bactrim (PCP)", "Valganciclovir (CMV)", "Nystatin/Fluconazole", "None"] },
  { k: "v2_post_inf_other", label: "other infections", options: undefined },
  { k: "v2_post_rej_suspicion", label: "clinical suspicion", options: undefined },
  { k: "v2_post_rej_biomarkers", label: "biomarkers dsa ddcfdna", options: undefined },
  { k: "v2_post_rej_us", label: "ultrasound perfusion", options: ["Normal", "Abnormal (Hydronephrosis/Collection)"] },
  { k: "v2_post_rej_bx", label: "biopsy banff scoring", options: undefined },
  { k: "v2_post_rej_class", label: "rejection classification", options: ["No Rejection", "TCMR (T-Cell Mediated)", "ABMR (Antibody-Mediated)", "Mixed", "Chronic Allograft Injury"] },
  { k: "v2_post_rej_tx", label: "active treatment protocol", options: undefined },
  { k: "v2_post_rej_response", label: "response assessment", options: undefined },
];
