"""
Patient Intake — 3-Agent Autonomous Reasoning System  v3.0.0
=============================================================

Architecture:
  All 3 agents run in PARALLEL after fetching patient data from MongoDB.
  A synthesis agent merges results → final analysis payload emitted.

Fixes in v3.0.0:
  - FULLY DYNAMIC: Zero hardcoded patient data. Every value injected from DB records.
  - max_tokens increased to 8000 (parallel agents) and 10000 (synthesis) to prevent truncation.
  - parse_llm_json is robust: handles truncated JSON, extracts partial objects safely.
  - Prompts use ONLY actual DB field values — no assumed medication names, conditions, or allergies.
  - All pre-computation helpers are data-driven (no fallback assumptions).
  - Briefing card in PA3 is fully generated by LLM from actual data — no template strings.
  - clean bullet-point / sentence output style enforced in system prompts.
"""

from __future__ import annotations

import asyncio
import json
import os
import re
import uuid
from datetime import datetime
from typing import Any, Dict, List, Optional, TypedDict

from fastapi import APIRouter, HTTPException
from loguru import logger
from pydantic import BaseModel

from langchain_groq import ChatGroq
from langchain_core.messages import HumanMessage, SystemMessage

from motor.motor_asyncio import AsyncIOMotorClient

# ============================================================
# ENVIRONMENT CONFIGURATION
# ============================================================

GROQ_API_KEY = os.getenv("GROQ_API_KEY")
MONGO_URI    = os.getenv("MONGO_URI")
MONGO_DB     = os.getenv("MONGO_DB", "doctorassistai")

mongo_client             = AsyncIOMotorClient(MONGO_URI)
mongo_db                 = mongo_client[MONGO_DB]
intake_collection        = mongo_db["patient_intake_assessments"]
patients_collection      = mongo_db["patients"]
agent_results_collection = mongo_db["intake_agent_results"]

# Parallel agents — larger token budget to prevent truncated JSON
llm = ChatGroq(
    model="llama-3.1-8b-instant",
    temperature=0.1,
    max_tokens=16384,  # CHANGED: from 12000 to maximum
    groq_api_key=GROQ_API_KEY,
)

llm_synthesis = ChatGroq(
    model="llama-3.3-70b-versatile",
    temperature=0.1,
    max_tokens=16384,  # CHANGED: from 15000 to maximum
    groq_api_key=GROQ_API_KEY,
)
router = APIRouter(prefix="", tags=["Patient Intake Agents"])


# ============================================================
# REQUEST / RESPONSE MODELS
# ============================================================

class IntakeAgentRequest(BaseModel):
    patient_id: str
    assessment_id: Optional[str] = None


class IntakeAgentResponse(BaseModel):
    patient_id:         str
    assessment_id:      str
    processed_at:       str
    processing_time_ms: int
    clinical_result:    Dict[str, Any]
    insurance_result:   Dict[str, Any]
    memory_result:      Dict[str, Any]
    synthesis_result:   Dict[str, Any]
    errors:             List[str]
    agent_timings:      Dict[str, float]


# ============================================================
# AGENT STATE
# ============================================================

class IntakeAgentState(TypedDict):
    patient_id:       str
    assessment_id:    str
    intake_record:    Dict
    patient_record:   Dict

    clinical_result:  Optional[Dict]
    insurance_result: Optional[Dict]
    memory_result:    Optional[Dict]
    synthesis_result: Optional[Dict]

    errors:           List[str]
    agent_timings:    Dict[str, float]


# ============================================================
# DATA FETCHERS
# ============================================================

async def fetch_latest_intake(patient_id: str, assessment_id: Optional[str] = None) -> Dict:
    try:
        query = {"patient_id": patient_id}
        if assessment_id:
            query["assessment_id"] = assessment_id
        cursor = intake_collection.find(query, {"_id": 0}).sort("created_at", -1).limit(1)
        records = await cursor.to_list(length=1)
        return records[0] if records else {}
    except Exception as e:
        logger.error(f"Intake fetch failed for {patient_id}: {e}")
        return {}


async def fetch_patient_base(patient_id: str) -> Dict:
    try:
        patient = await patients_collection.find_one({"patient_id": patient_id}, {"_id": 0})
        if not patient:
            patient = await patients_collection.find_one({"sys_user_id": patient_id}, {"_id": 0})
        return patient or {}
    except Exception as e:
        logger.error(f"Patient fetch failed for {patient_id}: {e}")
        return {}


# ============================================================
# ROBUST JSON PARSER
# Handles: markdown fences, leading text, truncated JSON
def parse_llm_json(text: str) -> Dict:
    """Robust JSON parser with aggressive recovery."""
    if not text:
        return {}
    
    text = text.strip()
    
    # Strip markdown fences and any leading/trailing text
    text = re.sub(r"```json\s*", "", text)
    text = re.sub(r"```\s*", "", text)
    
    # Try to find JSON after any explanatory text
    brace_start = text.find("{")
    if brace_start == -1:
        # Try to find any JSON-like structure
        json_match = re.search(r'\{.*\}', text, re.DOTALL)
        if json_match:
            text = json_match.group()
            brace_start = 0
        else:
            return {"raw_output": text}
    
    text = text[brace_start:]
    
    # Try direct parse first
    try:
        return json.loads(text)
    except json.JSONDecodeError as e:
        logger.debug(f"Initial JSON parse failed: {e}")
        
    # Try to repair common issues
    try:
        # Fix trailing commas
        text_fixed = re.sub(r',\s*}', '}', text)
        text_fixed = re.sub(r',\s*]', ']', text_fixed)
        return json.loads(text_fixed)
    except:
        pass
    
    # Try to extract complete JSON object by counting braces
    brace_count = 0
    in_string = False
    escape_next = False
    last_valid_pos = -1
    
    for i, char in enumerate(text):
        if escape_next:
            escape_next = False
            continue
        if char == '\\':
            escape_next = True
            continue
        if char == '"' and not escape_next:
            in_string = not in_string
            continue
        if not in_string:
            if char == '{':
                brace_count += 1
            elif char == '}':
                brace_count -= 1
                if brace_count == 0:
                    last_valid_pos = i
                    break
    
    if last_valid_pos != -1:
        candidate = text[:last_valid_pos + 1]
        try:
            return json.loads(candidate)
        except json.JSONDecodeError:
            pass
    
    # Try to repair by adding missing braces
    try:
        open_braces = text.count('{') - text.count('}')
        open_brackets = text.count('[') - text.count(']')
        open_quotes = text.count('"') % 2
        
        repaired = text
        if open_quotes == 1:
            repaired += '"'
        if open_brackets > 0:
            repaired += ']' * open_brackets
        if open_braces > 0:
            repaired += '}' * open_braces
        
        return json.loads(repaired)
    except:
        pass
    
    # Return raw output as last resort
    return {"raw_output": text[:1000] + "..." if len(text) > 1000 else text}
# ============================================================

def sv(value, default: str = "Not recorded") -> str:
    """Return string value or default if None/empty."""
    if value is None:
        return default
    s = str(value).strip()
    return s if s else default


def si_num(value, default=0):
    """Return numeric value safely."""
    try:
        return float(value)
    except (TypeError, ValueError):
        return default


# ============================================================
# DYNAMIC PRE-COMPUTATION HELPERS
# All values derived purely from DB records — no hardcoding
# ============================================================

def compute_gcs(neuro: Dict):
    """Compute GCS total and classification from DB neuro record."""
    try:
        eye    = int(neuro.get("gcsEye") or 0)
        verbal = int(neuro.get("gcsVerbal") or 0)
        motor  = int(neuro.get("gcsMotor") or 0)
        total  = eye + verbal + motor
        if total == 0:
            return "Unscored", "Unscored"
        if total >= 13:
            severity = "Mild TBI / Minor impairment"
        elif total >= 9:
            severity = "Moderate TBI"
        elif total >= 3:
            severity = "Severe TBI"
        else:
            severity = "Unscored"
        return total, severity
    except Exception:
        return "Unscored", "Unscored"


def classify_vitals(vitals: Dict, age_str: str, gender: str) -> Dict:
    """
    Returns per-vital classification dict derived entirely from DB vitals.
    No patient-specific assumptions — works for any patient data.
    """
    try:
        age_val = int(age_str) if age_str and str(age_str).isdigit() else 35
    except Exception:
        age_val = 35

    out = {}

    hr_raw = vitals.get("heartRate")
    if hr_raw is not None:
        try:
            hr = int(hr_raw)
            normal_lo, normal_hi = (60, 100)
            if hr < 50:
                out["heartRate"] = (f"Severe bradycardia ({hr} bpm)", "Critical")
            elif hr < 60:
                out["heartRate"] = (f"Bradycardia ({hr} bpm)", "Abnormal")
            elif hr <= 100:
                out["heartRate"] = (f"Normal sinus rhythm ({hr} bpm)", "Normal")
            elif hr <= 120:
                out["heartRate"] = (f"Tachycardia ({hr} bpm) — likely compensatory", "Abnormal")
            else:
                out["heartRate"] = (f"Severe tachycardia ({hr} bpm) — haemodynamic compromise", "Critical")
        except Exception:
            pass

    sbp_raw = vitals.get("systolicBP")
    dbp_raw = vitals.get("diastolicBP")
    if sbp_raw is not None and dbp_raw is not None:
        try:
            sbp, dbp = int(sbp_raw), int(dbp_raw)
            pp = sbp - dbp
            pp_pattern = "narrow (<25 mmHg — obstructive/cardiogenic pattern)" if pp < 25 else f"wide ({pp} mmHg — distributive pattern)"
            if sbp < 90:
                out["bp"] = (f"Hypotensive shock — SBP {sbp} mmHg below 90 threshold. Pulse pressure {pp} mmHg ({pp_pattern}).", "Critical")
            elif sbp < 120:
                out["bp"] = (f"Normal BP ({sbp}/{dbp} mmHg)", "Normal")
            elif sbp < 140:
                out["bp"] = (f"High-normal BP ({sbp}/{dbp} mmHg)", "Abnormal")
            else:
                out["bp"] = (f"Hypertensive ({sbp}/{dbp} mmHg)", "Abnormal")
        except Exception:
            pass

    spo2_raw = vitals.get("spo2")
    if spo2_raw is not None:
        try:
            s = int(spo2_raw)
            if s >= 95:
                out["spo2"] = (f"Adequate oxygenation ({s}%)", "Normal")
            elif s >= 90:
                out["spo2"] = (f"Mild hypoxaemia ({s}%) — supplemental O2 required", "Abnormal")
            elif s >= 85:
                out["spo2"] = (f"Moderate hypoxaemia ({s}%) — high-flow O2 / consider NIV", "Critical")
            else:
                out["spo2"] = (f"Severe hypoxaemia ({s}%) — immediate intubation risk", "Critical")
        except Exception:
            pass

    rr_raw = vitals.get("respiratoryRate")
    if rr_raw is not None:
        try:
            rr = int(rr_raw)
            if rr < 12:
                out["respiratoryRate"] = (f"Bradypnoea ({rr}/min) — CNS depression risk", "Critical")
            elif rr <= 20:
                out["respiratoryRate"] = (f"Normal respiratory rate ({rr}/min)", "Normal")
            elif rr <= 25:
                out["respiratoryRate"] = (f"Tachypnoea ({rr}/min) — early respiratory compromise", "Abnormal")
            else:
                out["respiratoryRate"] = (f"Severe tachypnoea ({rr}/min) — imminent respiratory failure risk", "Critical")
        except Exception:
            pass

    temp_raw = vitals.get("temperature")
    if temp_raw is not None:
        try:
            t = float(temp_raw)
            if t < 35.0:
                out["temperature"] = (f"Severe hypothermia ({t}°C)", "Critical")
            elif t < 36.0:
                out["temperature"] = (f"Hypothermia ({t}°C) — trauma-related thermolysis", "Abnormal")
            elif t <= 37.5:
                out["temperature"] = (f"Normal temperature ({t}°C)", "Normal")
            elif t <= 38.5:
                out["temperature"] = (f"Low-grade fever ({t}°C) — systemic stress response", "Abnormal")
            else:
                out["temperature"] = (f"Fever ({t}°C) — infection or central fever", "Critical")
        except Exception:
            pass

    return out


def compute_shock_index(vitals: Dict) -> tuple:
    """Compute Shock Index = HR / SBP from DB vitals."""
    try:
        hr  = float(vitals.get("heartRate") or 0)
        sbp = float(vitals.get("systolicBP") or 1)
        if sbp == 0:
            return "N/A", "Unable to compute (SBP=0)"
        si = round(hr / sbp, 2)
        if si < 0.9:
            interp = "Normal (<0.9) — haemodynamically stable"
        elif si <= 1.0:
            interp = "Borderline (0.9–1.0) — early shock risk"
        elif si <= 1.4:
            interp = "Class II shock (1.0–1.4) — significant haemorrhage"
        else:
            interp = "Severe shock / exsanguination risk (>1.4)"
        return si, interp
    except Exception:
        return "N/A", "Unable to compute"


def compute_map(vitals: Dict) -> tuple:
    """Compute Mean Arterial Pressure from DB vitals."""
    try:
        sbp = float(vitals.get("systolicBP") or 0)
        dbp = float(vitals.get("diastolicBP") or 0)
        if sbp == 0 and dbp == 0:
            return "N/A", "Unable to compute"
        map_val = round(dbp + (sbp - dbp) / 3, 1)
        interp = (
            "Adequate cerebral perfusion (MAP ≥70 mmHg)"
            if map_val >= 70
            else f"Insufficient cerebral perfusion — CRITICAL (MAP={map_val} <70 mmHg)"
        )
        return map_val, interp
    except Exception:
        return "N/A", "Unable to compute"


def compute_last_dose_timing(last_dose_str: str) -> tuple:
    """
    Compute hours since last medication dose.
    Returns (hours_since_str, timing_note).
    Fully dynamic — works for any last-dose timestamp from DB.
    """
    if not last_dose_str or last_dose_str in ("Not recorded", "Unknown", ""):
        return "Unknown", "Last dose timing not recorded — cannot assess pharmacological activity"
    try:
        last_dose_dt = datetime.fromisoformat(str(last_dose_str))
        now = datetime.now()
        hours_since = round((now - last_dose_dt).total_seconds() / 3600, 1)
        return str(hours_since), f"Approximately {hours_since} hours since last recorded dose"
    except Exception:
        return "Unknown", f"Could not parse last dose timestamp: {last_dose_str}"


def estimate_treatment_costs_by_type(accident_type: str, injury_type: str) -> Dict:
    """
    Return cost estimates based on actual accident/injury type from DB.
    No hardcoded clinical assumptions — purely financial reference ranges.
    """
    base = {
        "er_admission":      {"min": 10000, "max": 40000, "label": "ER Admission"},
        "icu_per_day":       {"min": 20000, "max": 80000, "label": "ICU per day"},
        "general_surgery":   {"min": 80000, "max": 400000, "label": "Emergency Surgery"},
        "ct_imaging":        {"min": 5000,  "max": 20000,  "label": "CT / Imaging"},
        "blood_products":    {"min": 8000,  "max": 25000,  "label": "Blood Products"},
        "icu_5_days":        {"min": 100000,"max": 400000, "label": "5-Day ICU Estimate"},
        "specialist_consult":{"min": 2000,  "max": 8000,   "label": "Specialist Consultations"},
        "ambulance":         {"min": 1000,  "max": 5000,   "label": "Ambulance Transport"},
    }
    # Bump surgery estimate for head/neuro injury keywords
    neuro_keywords = ["head", "brain", "neuro", "cranial", "spine", "spinal"]
    combined = f"{accident_type} {injury_type}".lower()
    if any(k in combined for k in neuro_keywords):
        base["general_surgery"] = {"min": 150000, "max": 600000, "label": "Emergency / Neurosurgery"}

    return base


def parse_coverage_limit(coverage_limit_raw) -> tuple:
    """Parse coverage limit from any string/number format into (numeric, formatted_str)."""
    if coverage_limit_raw is None:
        return 0, "Not provided"
    try:
        cl_num = float(re.sub(r"[^\d.]", "", str(coverage_limit_raw)))
        cl_fmt = f"₹{cl_num:,.0f}"
        return cl_num, cl_fmt
    except Exception:
        return 0, str(coverage_limit_raw)


# ============================================================
# BASE AGENT
# ============================================================
class BaseIntakeAgent:
    def __init__(self, llm_instance):
        self.llm = llm_instance

    def _elapsed(self, start: float) -> float:
        """Calculate elapsed time in milliseconds."""
        return round((datetime.now().timestamp() - start) * 1000, 1)

    async def _invoke(self, system: str, user: str, max_retries: int = 3) -> Dict:
        """Invoke LLM with automatic retry on malformed JSON."""
        last_error = None
        last_response = None
        
        for attempt in range(max_retries):
            try:
                response = await self.llm.ainvoke([
                    SystemMessage(content=system),
                    HumanMessage(content=user),
                ])
                
                last_response = response.content
                parsed = parse_llm_json(response.content)
                
                # Check if we got valid JSON with required fields
                if self._is_valid_response(parsed):
                    return parsed
                else:
                    last_error = f"Response missing required fields. Got: {list(parsed.keys()) if parsed else 'empty'}"
                    
                    # On retry, add stronger instruction based on what's missing
                    if attempt < max_retries - 1:
                        if "raw_output" in parsed:
                            user += f"\n\nYour previous response was not valid JSON. You wrote: '{parsed['raw_output'][:200]}...'\n"
                        user += "\nCRITICAL INSTRUCTION: You MUST return ONLY valid JSON. Start with '{' and end with '}'. No markdown, no code blocks, no explanatory text before or after the JSON. The entire response must be parseable by json.loads()."
                        
            except Exception as e:
                last_error = str(e)
                last_response = None
                if attempt < max_retries - 1:
                    logger.warning(f"{self.agent_id} attempt {attempt + 1} failed with exception: {last_error}. Retrying...")
                    user += "\n\nCRITICAL: Your previous response caused an error. Return ONLY valid JSON. No other text."
        
        # Return a minimal valid structure on final failure
        logger.error(f"{self.agent_id} failed after {max_retries} attempts. Last error: {last_error}")
        logger.error(f"Last response: {last_response[:500] if last_response else 'None'}")
        
        return {
            "agent": getattr(self, 'agent_id', 'unknown'),
            "patient_id": "unknown", 
            "assessment_id": "unknown",
            "error": f"Failed to generate valid JSON after {max_retries} attempts. Last error: {last_error}",
            "raw_response": last_response[:1000] if last_response else None
        }

    def _is_valid_response(self, parsed: Dict) -> bool:
        """Validate that response has expected structure."""
        if not parsed or len(parsed) == 0:
            return False
        
        # If we have raw_output only, that means parsing failed
        if "raw_output" in parsed and len(parsed) == 1:
            return False
        
        # Check for error condition
        if "error" in parsed:
            return False
        
        # For PA1 (Clinical Agent), check for required fields
        if hasattr(self, 'agent_id') and self.agent_id == "PA1":
            required_fields = ["triage", "haemodynamic_status", "neurological_assessment"]
            for field in required_fields:
                if field not in parsed:
                    logger.warning(f"PA1 missing required field: {field}")
                    return False
        
        # For PA2 (Insurance Agent), check for required fields  
        elif hasattr(self, 'agent_id') and self.agent_id == "PA2":
            required_fields = ["policy_verification", "financial_summary", "cashless_protocol"]
            for field in required_fields:
                if field not in parsed:
                    logger.warning(f"PA2 missing required field: {field}")
                    return False
        
        # For PA3 (Memory Agent), check for required fields
        elif hasattr(self, 'agent_id') and self.agent_id == "PA3":
            required_fields = ["medication_safety_review", "allergy_safety_analysis", "patient_safety_score"]
            for field in required_fields:
                if field not in parsed:
                    logger.warning(f"PA3 missing required field: {field}")
                    return False
        
        return True
# ============================================================
class ClinicalIntakeAgent(BaseIntakeAgent):
    agent_id = "PA1"

    async def run(self, state: IntakeAgentState) -> Dict:
        logger.info(f"{self.agent_id} · ClinicalIntakeAgent — START")
        t0 = datetime.now().timestamp()

        intake  = state.get("intake_record", {})
        patient = state.get("patient_record", {})

        clinical  = intake.get("clinical_assessment", {})
        vitals    = clinical.get("vitals", {})
        neuro     = clinical.get("neurological_status", {})
        injury    = clinical.get("injury_symptoms", {})
        crit_syms = clinical.get("critical_symptoms", {})

        age_str    = sv(patient.get("age"), "Unknown")
        gender_str = sv(patient.get("gender"), "Unknown")

        gcs_total, gcs_class = compute_gcs(neuro)
        vital_classes         = classify_vitals(vitals, age_str, gender_str)
        si, si_interp         = compute_shock_index(vitals)
        map_val, map_interp   = compute_map(vitals)

        # Vital display helpers
        def vc(key):
            c = vital_classes.get(key, ("Not recorded", "Unknown"))
            return c[0], c[1]

        accident_type      = sv(patient.get("accidentDetails", {}).get("accidentType"))
        condition_on_scene = sv(patient.get("accidentDetails", {}).get("condition"))

        system = (
            "You are a senior emergency physician AI. "
            "You receive REAL patient data from a hospital intake system. "
            "Perform deep clinical reasoning on the ACTUAL values provided — do NOT invent values. "
            "Every recommendation must cite the exact value from the data above it. "
            "Never use placeholder text. If a value is 'Not recorded', state that explicitly and note the clinical risk of missing data. "
            "Output clear, specific bullet-point style results inside the JSON string fields — "
            "each field should read as a clinical sentence, not a generic label. "
            "Respond ONLY with valid JSON. No markdown, no preamble."
        )

        # FIXED: This prompt is now properly indented inside the method
        prompt = f"""
CLINICAL AGENT ANALYSIS for patient {sv(state["patient_id"])}

REAL PATIENT DATA (use ONLY these values):
- Demographics: Age={age_str}, Gender={gender_str}, Accident={accident_type}
- Vitals: HR={sv(vitals.get("heartRate"))}, BP={sv(vitals.get("systolicBP"))}/{sv(vitals.get("diastolicBP"))}, SpO2={sv(vitals.get("spo2"))}, RR={sv(vitals.get("respiratoryRate"))}, Temp={sv(vitals.get("temperature"))}
- Neuro: GCS Eye={sv(neuro.get("gcsEye"))}, Verbal={sv(neuro.get("gcsVerbal"))}, Motor={sv(neuro.get("gcsMotor"))}, Total={gcs_total}
- Injuries: Type={sv(injury.get("injuryType"))}, Bleeding={sv(injury.get("externalBleeding"))}
- Critical Symptoms: Chest Pain={sv(crit_syms.get("chestPain"))}, Breathing Difficulty={sv(crit_syms.get("breathingDifficulty"))}

Pre-computed: Shock Index={si}, MAP={map_val}

Generate JSON with these sections:
1. triage (level, rationale)
2. haemodynamic_status (shock_index, map, atls_shock_class, resuscitation_strategy)
3. neurological_assessment (gcs_total, intubation_indicated, pupil_reaction)
4. injury_assessment (list with ais_score, severity)
5. vital_analysis (array with each vital's classification and intervention)
6. revised_trauma_score (rts_value, survival_probability_percent)
7. imaging_orders (priority order)
8. protocol_activated (name, steps)
9. primary_diagnosis, emergency_type, severity

Return ONLY valid JSON. No markdown, no explanations.
"""
        result = await self._invoke(system, prompt)
        elapsed = self._elapsed(t0)
        logger.info(f"{self.agent_id} · ClinicalIntakeAgent — DONE ({elapsed}ms)")
        
        # Check if result is just raw_output (meaning parse failed)
        if "raw_output" in result and len(result) == 1:
            deeper_parse = parse_llm_json(result["raw_output"])
            if "raw_output" not in deeper_parse:
                result = deeper_parse
                
        return {"clinical_result": result, "timing": elapsed}
# In ClinicalIntakeAgent.run(), replace the enormous prompt with a more focused one:




# ============================================================
# PA2 · INSURANCE AGENT — fully dynamic, per-service cost analysis
# ============================================================

class InsuranceIntakeAgent(BaseIntakeAgent):
    agent_id = "PA2"

    async def run(self, state: IntakeAgentState) -> Dict:
        logger.info(f"{self.agent_id} · InsuranceIntakeAgent — START")
        t0 = datetime.now().timestamp()

        intake   = state.get("intake_record", {})
        patient  = state.get("patient_record", {})
        ins_data = intake.get("insurance_verification", {})

        identification = ins_data.get("identification", {})
        ins_details    = ins_data.get("insurance_details", {})
        coverage       = ins_data.get("coverage_details", {})
        authorization  = ins_data.get("authorization", {})
        contact_notes  = ins_data.get("contact_notes", {})

        coverage_limit_raw = coverage.get("coverageLimit")
        cl_num, cl_formatted = parse_coverage_limit(coverage_limit_raw)

        clinical   = intake.get("clinical_assessment", {})
        injury     = clinical.get("injury_symptoms", {})
        accident_type = sv(patient.get("accidentDetails", {}).get("accidentType"), "General")
        injury_type   = sv(injury.get("injuryType"), "General")

        est_costs  = estimate_treatment_costs_by_type(accident_type, injury_type)
        total_min  = sum(v["min"] for v in est_costs.values())
        total_max  = sum(v["max"] for v in est_costs.values())
        shortfall_min = max(0, total_min - cl_num)
        shortfall_max = max(0, total_max - cl_num)

        # Build cost table dynamically
        cost_table_lines = []
        for k, v in est_costs.items():
            cost_table_lines.append(
                f"  {v['label']:<35}: ₹{v['min']:>8,} – ₹{v['max']:>8,}"
            )
        cost_table = "\n".join(cost_table_lines)

        preauth_ref = f"PREAUTH-{datetime.now().strftime('%Y%m%d')}-{uuid.uuid4().hex[:5].upper()}"

        system = (
            "You are a hospital insurance verification and pre-authorization AI. "
            "You receive REAL insurance data from patient intake forms. "
            "Analyze each field exactly as submitted — do NOT invent policy details, TPA names, or sub-limits. "
            "For every service, compute actual coverage against the submitted limit. "
            "If data is missing, flag it explicitly as a verification gap. "
            "Write each JSON string field as a clear, specific sentence — not a generic label. "
            "Respond ONLY with valid JSON. No markdown, no preamble."
        )

        prompt = f"""
You are the INSURANCE AGENT (PA2) for patient {sv(state["patient_id"])}.
All values below come directly from the patient intake database. Reason only from these values.
Do NOT invent insurance details not present in the data.

════════════════════════════════════════════════════
PATIENT (from DB)
════════════════════════════════════════════════════
Name             : {sv(patient.get("fullName"))}
Age              : {sv(patient.get("age"))} years
Assessment Date  : {sv(intake.get("assessment_date"))}
Accident Type    : {accident_type}
Injury Type      : {injury_type}

════════════════════════════════════════════════════
SUBMITTED INSURANCE DATA (verbatim from intake form)
════════════════════════════════════════════════════
ID Type          : {sv(identification.get("idType"))}
ID Number        : {sv(identification.get("idNumber"))}
Insurance Avail. : {sv(ins_details.get("insuranceAvailable"))}
Provider         : {sv(ins_details.get("providerName"))}
Policy Number    : {sv(ins_details.get("policyNumber"))}
Policy Holder    : {sv(ins_details.get("policyHolderName"))}
Relationship     : {sv(ins_details.get("relationshipToPatient"))}
Policy Valid     : {sv(coverage.get("policyValid"))}
Emergency Cov.   : {sv(coverage.get("emergencyCoverage"))}
Coverage Limit   : {sv(coverage_limit_raw)} = {cl_formatted}
Cashless Facility: {sv(coverage.get("cashlessFacility"))}
Pre-Auth Required: {sv(authorization.get("preAuthRequired"))}
Pre-Auth Status  : {sv(authorization.get("preAuthStatus"))}
Insurance Contact: {sv(contact_notes.get("insuranceContact"))}
Remarks          : {sv(contact_notes.get("insuranceRemarks"), "None")}

════════════════════════════════════════════════════
ESTIMATED COSTS FOR THIS PATIENT (based on {accident_type} + {injury_type})
════════════════════════════════════════════════════
{cost_table}
  ─────────────────────────────────────────────────
  TOTAL ESTIMATED RANGE                    : ₹{total_min:>8,} – ₹{total_max:>8,}
  COVERAGE LIMIT (submitted)               : {cl_formatted}
  POTENTIAL SHORTFALL                      : ₹{shortfall_min:>8,} – ₹{shortfall_max:>8,}

════════════════════════════════════════════════════
YOUR TASKS — use only submitted data above
════════════════════════════════════════════════════

TASK 1 — POLICY VALIDITY
  Assess whether submitted data constitutes verified coverage.
  List specific verification gaps (missing TPA name, no expiry date, etc.).

TASK 2 — PER-SERVICE COVERAGE
  For EACH service in the cost table above:
  - Status based on submitted data (emergency coverage = {sv(coverage.get("emergencyCoverage"))})
  - Estimated cost range (from table above)
  - Amount covered up to limit ({cl_formatted})
  - Patient out-of-pocket liability
  - Whether separate pre-auth is needed
  - Any common exclusions for this type of service

TASK 3 — CASHLESS PROTOCOL
  Cashless = {sv(coverage.get("cashlessFacility"))}.
  If Yes: exact steps for activation, documents needed now, expected approval timeline.
  If No/Unknown: reimbursement mode steps.

TASK 4 — SHORTFALL AND DEPOSIT RECOMMENDATION
  Given limit {cl_formatted} vs estimate ₹{total_min:,}–₹{total_max:,}:
  Compute exact shortfall. Which services exhaust limit first?
  Recommend patient deposit amount for billing team.

TASK 5 — PRE-AUTHORIZATION RECORD
  Reference: {preauth_ref}
  List authorized services with amounts. Validity 72 hours.
  Note: Pre-Auth Required = {sv(authorization.get("preAuthRequired"))} — explain operational meaning.

TASK 6 — FLAGGED ISSUES
  Flag each specific data gap or risk with severity (Blocking/Advisory/Minor).
  Include workaround for each.

TASK 7 — BILLING TEAM INSTRUCTION
  Time-sequenced steps for the next 30 minutes. Name documents, calls, forms.

Return ONLY valid JSON:
{{
  "agent": "PA2-InsuranceAgent",
  "patient_id": "{sv(state["patient_id"])}",
  "assessment_id": "{sv(state["assessment_id"])}",
  "timestamp": "{datetime.now().isoformat()}",
  "policy_verification": {{
    "insurance_available": "{sv(ins_details.get("insuranceAvailable"))}",
    "provider": "{sv(ins_details.get("providerName"))}",
    "policy_number": "{sv(ins_details.get("policyNumber"))}",
    "policy_valid_as_submitted": "{sv(coverage.get("policyValid"))}",
    "validity_status": "Active|Likely Active|Unknown|Expired|Suspended",
    "verification_completeness": "Full|Partial|Minimal",
    "verification_gaps": ["List specific missing fields from submitted data"],
    "policy_holder": "{sv(ins_details.get("policyHolderName"))}",
    "relationship": "{sv(ins_details.get("relationshipToPatient"))}",
    "identity_document": "{sv(identification.get("idType"))} — {sv(identification.get("idNumber"))}",
    "identity_acceptable": true,
    "identity_notes": "Assessment of submitted ID type acceptability for insurance claim"
  }},
  "financial_summary": {{
    "coverage_limit": "{cl_formatted}",
    "coverage_limit_numeric": {cl_num},
    "estimated_treatment_min": {total_min},
    "estimated_treatment_max": {total_max},
    "estimated_shortfall_min": {shortfall_min},
    "estimated_shortfall_max": {shortfall_max},
    "recommended_patient_deposit": "Compute from shortfall range"
  }},
  "coverage_assessment": [
    {{
      "service": "Service name from cost table",
      "status": "Covered|Likely Covered|Unknown|Not Covered",
      "estimated_cost_range": "₹X – ₹Y from cost table",
      "amount_covered": "₹Z (up to policy limit)",
      "patient_liability": "₹0 or specific amount",
      "pre_auth_needed_for_this_service": false,
      "typical_exclusions": "Common exclusion for this service type",
      "specific_notes": "Specific note based on submitted coverage data — not generic"
    }}
  ],
  "cashless_protocol": {{
    "cashless_facility": "{sv(coverage.get("cashlessFacility"))}",
    "cashless_decision": "Activate Cashless|Activate Reimbursement|Investigate",
    "activation_steps": ["Step 1", "Step 2"],
    "documents_needed_now": ["Document 1", "Document 2"],
    "expected_approval_minutes": 0,
    "tpa_name": "From submitted data or 'Not provided in intake form'",
    "tpa_contact": "{sv(contact_notes.get("insuranceContact"))}",
    "out_of_pocket_risk": "None|Low|Moderate|High|Unknown",
    "coverage_limit_submitted": "{cl_formatted}",
    "instructions": "Specific cashless or reimbursement activation steps"
  }},
  "pre_authorization": {{
    "preauth_reference": "{preauth_ref}",
    "authorized_services": [
      {{"service": "Service name", "estimated_amount": "₹amount", "notes": "specific note"}}
    ],
    "total_authorized_amount": "{cl_formatted}",
    "validity_hours": 72,
    "issued_at": "{datetime.now().isoformat()}",
    "billing_contact": "{sv(contact_notes.get("insuranceContact"))}",
    "preauth_required": "{sv(authorization.get("preAuthRequired"))}",
    "preauth_operational_meaning": "What this pre-auth status means for this admission specifically"
  }},
  "flagged_issues": [
    {{
      "issue": "Specific issue name based on submitted data",
      "severity": "Blocking|Advisory|Minor",
      "detail": "Why this is a problem for this patient",
      "workaround": "Specific action to resolve"
    }}
  ],
  "billing_team_instruction": "Numbered, time-sequenced steps with specific document names and contact numbers",
  "insurance_remarks": "{sv(contact_notes.get("insuranceRemarks"), "None")}",
  "coverage_confidence": 0.0,
  "overall_status": "Verified — Cashless Eligible|Verified — Reimbursement Only|Partial Coverage|Unable to Verify|Not Covered",
  "dashboard_badge": "CASHLESS APPROVED|REIMBURSEMENT MODE|VERIFY MANUALLY|NO INSURANCE",
  "load_percentage": 0
}}
"""
        result = await self._invoke(system, prompt)
        elapsed = self._elapsed(t0)
        logger.info(f"{self.agent_id} · InsuranceIntakeAgent — DONE ({elapsed}ms)")
        
        # Check if result is just raw_output (meaning parse failed)
        if "raw_output" in result and len(result) == 1:
            deeper_parse = parse_llm_json(result["raw_output"])
            if "raw_output" not in deeper_parse:
                result = deeper_parse
                
        return {"insurance_result": result, "timing": elapsed}

# ============================================================
# PA3 · MEMORY AGENT — fully dynamic, no hardcoded drug names
# ============================================================

class MemoryIntakeAgent(BaseIntakeAgent):
    agent_id = "PA3"

    async def run(self, state: IntakeAgentState) -> Dict:
        logger.info(f"{self.agent_id} · MemoryIntakeAgent — START")
        t0 = datetime.now().timestamp()

        intake   = state.get("intake_record", {})
        patient  = state.get("patient_record", {})
        med_hist = intake.get("medical_history", {})

        bg        = med_hist.get("medical_background", {})
        meds      = med_hist.get("medications", {})
        allergies = med_hist.get("allergies", {})
        surgical  = med_hist.get("surgical_history", {})
        add_info  = med_hist.get("additional_medical_info", {})
        clinical  = intake.get("clinical_assessment", {})
        vitals    = clinical.get("vitals", {})
        crit_syms = clinical.get("critical_symptoms", {})

        # Dynamic medication timing — works for any drug
        last_dose_str = sv(meds.get("lastDoseTaken"), "")
        hours_since, timing_note = compute_last_dose_timing(last_dose_str)

        # Blood group — from DB, no default
        blood_group = sv(add_info.get("bloodGroup"), "Not recorded")

        # Current medications — from DB only
        current_meds  = sv(meds.get("currentMeds"), "None recorded")
        med_dosage    = sv(meds.get("medDosage"), "Not recorded")
        med_frequency = sv(meds.get("medFrequency"), "Not recorded")

        # Conditions — from DB only
        conditions       = sv(bg.get("medicalConditions"), "None recorded")
        chronic_illness  = sv(bg.get("chronicIllness"), "Not recorded")
        chronic_details  = sv(bg.get("chronicIllnessDetails"), "None")

        # Allergies — from DB only
        drug_allergy         = sv(allergies.get("drugAllergies"), "Not recorded")
        drug_allergy_details = sv(allergies.get("drugAllergiesDetails"), "None")
        food_allergy         = sv(allergies.get("foodAllergies"), "Not recorded")
        food_allergy_details = sv(allergies.get("foodAllergiesDetails"), "None")
        other_allergy        = sv(allergies.get("otherAllergies"), "None")

        # Surgical history — from DB only
        prev_surgeries = sv(surgical.get("previousSurgeries"), "Not recorded")
        surgery_type   = sv(surgical.get("surgeryType"), "None")
        surgery_date   = sv(surgical.get("surgeryDate"), "Unknown")

        # Additional — from DB only
        pregnancy_status = sv(add_info.get("pregnancyStatus"), "Not recorded")
        family_history   = sv(add_info.get("familyHistory"), "None recorded")

        accident_type = sv(patient.get("accidentDetails", {}).get("accidentType"), "Unknown")

        system = (
            "You are a clinical pharmacology and medical history AI for an emergency hospital. "
            "You receive REAL patient medical history from a database. "
            "Reason ONLY from the actual data provided — do NOT assume any drug name, condition, "
            "or allergy not explicitly stated in the data. "
            "If a field says 'None recorded' or 'Not recorded', analyze the risk of that data gap. "
            "For each medication listed, analyze its pharmacokinetics and interactions with standard "
            "emergency drugs using the actual drug name given. "
            "Write each JSON string field as a specific, actionable clinical sentence. "
            "Respond ONLY with valid JSON. No markdown, no preamble."
        )

        prompt = f"""
You are the MEMORY AGENT (PA3) for patient {sv(state["patient_id"])}.
All values below are from the patient database. Reason ONLY from these values.
Do NOT assume any medication, condition, or allergy not stated below.

════════════════════════════════════════════════════
PATIENT IDENTITY (from DB)
════════════════════════════════════════════════════
Patient ID       : {sv(state["patient_id"])}
Name             : {sv(patient.get("fullName", patient.get("name")))}
Age              : {sv(patient.get("age"))} years
Gender           : {sv(patient.get("gender"))}
Blood Group      : {blood_group}
Accident Type    : {accident_type}
Clinical Notes   : {sv(crit_syms.get("clinicalNotes"), "None recorded")}
Current SpO2     : {sv(vitals.get("spo2"), "Not recorded")}%
Current BP       : {sv(vitals.get("systolicBP"), "Not recorded")}/{sv(vitals.get("diastolicBP"), "Not recorded")} mmHg

════════════════════════════════════════════════════
MEDICAL BACKGROUND (from DB)
════════════════════════════════════════════════════
Known Conditions : {conditions}
Chronic Illness  : {chronic_illness}
Illness Details  : {chronic_details}

════════════════════════════════════════════════════
MEDICATIONS (from DB)
════════════════════════════════════════════════════
Current Meds     : {current_meds}
Dose             : {med_dosage}
Frequency        : {med_frequency}
Last Dose        : {last_dose_str if last_dose_str else "Not recorded"}
Timing Note      : {timing_note}

════════════════════════════════════════════════════
ALLERGIES (from DB)
════════════════════════════════════════════════════
Drug Allergies   : {drug_allergy} — {drug_allergy_details}
Food Allergies   : {food_allergy} — {food_allergy_details}
Other Allergies  : {other_allergy}

════════════════════════════════════════════════════
SURGICAL HISTORY (from DB)
════════════════════════════════════════════════════
Previous Surgery : {prev_surgeries}
Surgery Type     : {surgery_type}
Surgery Date     : {surgery_date}

════════════════════════════════════════════════════
ADDITIONAL INFO (from DB)
════════════════════════════════════════════════════
Blood Group      : {blood_group}
Pregnancy Status : {pregnancy_status}
Family History   : {family_history}

════════════════════════════════════════════════════
YOUR TASKS
════════════════════════════════════════════════════
Base ALL analysis on the values above. Do not invent data.

TASK 1 — CHRONIC CONDITIONS IN TRAUMA CONTEXT
  For each condition listed in 'Known Conditions' and 'Chronic Illness':
  - Explain how this specific condition modifies emergency trauma treatment.
  - What BP / physiological targets are changed by this condition?
  - What drugs must be avoided because of this condition?
  - What monitoring parameters are added because of this condition?
  If no conditions are recorded, state this clearly and analyze the risk of that data gap.

TASK 2 — MEDICATION PHARMACOLOGY IN EMERGENCY
  For each drug in 'Current Meds = {current_meds}':
  - Drug class and mechanism of action.
  - Is it still pharmacologically active given timing note above?
  - How does it affect: vasopressors, anaesthesia, haemorrhagic shock management?
  - Interactions with: noradrenaline, dopamine, propofol, ketamine, fentanyl, morphine,
    mannitol, tranexamic acid, hypertonic saline.
  - Should it be continued, held, or dose-adjusted in emergency?
  If 'None recorded' for medications, state this and flag the data gap.

TASK 3 — ALLERGY SAFETY ANALYSIS
  Based on drug allergy = '{drug_allergy}' and food allergy = '{food_allergy}':
  - Do any allergies implicate standard emergency drugs (contrast dye, NSAIDs, antibiotics, anaesthetics)?
  - Generate a safe drug list for: analgesia, anaesthesia/RSI, antibiotics, anti-emetics, BP management.
  - List drugs to avoid with specific reasons.
  - If 'Not recorded', flag as HIGH RISK data gap — state what must be asked before drug administration.

TASK 4 — BLOOD GROUP MANAGEMENT
  Blood Group = {blood_group}.
  If blood group is recorded:
  - Compatible donor types.
  - Emergency uncross-matched sequence.
  - Blood product preparation for suspected bleeding (from injury data: external bleeding = {sv(clinical.get("injury_symptoms", {}).get("externalBleeding"))}, internal = {sv(clinical.get("injury_symptoms", {}).get("internalBleeding"))}).
  - MTP trigger criteria — are they met based on shock index and injury data?
  If not recorded: flag as CRITICAL data gap and state emergency uncross-matched fallback.

TASK 5 — SURGICAL HISTORY IMPACT
  Previous surgeries = {prev_surgeries}, type = {surgery_type}.
  - Any implants or hardware that affect imaging (MRI contraindications)?
  - Any prior anaesthetic complications on record?
  - Any prior surgery site that increases risk in current trauma?

TASK 6 — FAMILY HISTORY RISK
  Family history = {family_history}.
  - Does family history suggest any genetic predispositions relevant to emergency care?
  - What cardiac/metabolic monitoring should be added because of this history?
  - Patient age = {sv(patient.get("age"))}, gender = {sv(patient.get("gender"))} — what ASCVD or other risk elevation?

TASK 7 — TREATING TEAM BRIEFING CARD
  Generate 8 bullet points. Each must:
  - Start with an emoji and category label
  - Reference actual DB values (not generic statements)
  - State what to do immediately
  Example format: "💊 Medications: Patient is on [actual drug from DB] — [specific action]"
  Do NOT use placeholder text like "[drug name]". Use actual values.
  If a value is 'Not recorded', say: "⚠️ [Category]: Not recorded — must verify before [specific action]"

TASK 8 — PATIENT SAFETY SCORE
  Score 0.0 (many concerns) to 1.0 (no concerns).
  Breakdown: medications (out of 0.4) + allergies (out of 0.3) + history (out of 0.3).
  Base scoring on actual recorded data, not assumptions.

Return ONLY valid JSON:
{{
  "agent": "PA3-MemoryAgent",
  "patient_id": "{sv(state["patient_id"])}",
  "assessment_id": "{sv(state["assessment_id"])}",
  "timestamp": "{datetime.now().isoformat()}",
  "chronic_condition_analysis": [
    {{
      "condition": "Exact condition name from DB or 'None recorded'",
      "trauma_modification": "Specific impact on emergency treatment",
      "physiological_targets_changed": "What targets are different because of this condition",
      "drugs_to_avoid": ["Drug name + specific reason from this condition"],
      "additional_monitoring": ["Specific parameter + frequency"],
      "data_gap_risk": "Risk level if this field was empty"
    }}
  ],
  "medication_safety_review": {{
    "medications_recorded": "{current_meds}",
    "dose": "{med_dosage}",
    "frequency": "{med_frequency}",
    "last_dose": "{last_dose_str if last_dose_str else "Not recorded"}",
    "hours_since_dose": "{hours_since}",
    "timing_note": "{timing_note}",
    "pharmacologically_active": true,
    "drug_class": "Derived from actual drug name above",
    "mechanism": "Mechanism of the actual drug listed",
    "haemodynamic_impact": "How this drug affects emergency haemodynamic management",
    "drug_interactions": [
      {{
        "emergency_drug": "Named emergency drug",
        "interaction_type": "Pharmacodynamic|Pharmacokinetic|Additive|None",
        "mechanism": "Specific mechanism involving actual current medication",
        "clinical_effect": "Specific effect on this patient",
        "management": "Specific management action"
      }}
    ],
    "emergency_action": "Continue|Hold|Dose-adjust|Monitor",
    "emergency_action_rationale": "Specific reason based on actual drug and timing",
    "data_gap_risk": "Risk if medications field was empty"
  }},
  "allergy_safety_analysis": {{
    "drug_allergy_status": "{drug_allergy}",
    "drug_allergy_details": "{drug_allergy_details}",
    "food_allergy_status": "{food_allergy}",
    "food_allergy_details": "{food_allergy_details}",
    "contrast_dye_risk": "Low|Moderate|High — rationale from actual allergy data",
    "safe_drug_list": {{
      "analgesia": ["Drug + dose — safe based on allergy profile"],
      "rsi_induction": ["Preferred agent + rationale from allergy data"],
      "rsi_paralytic": ["Safe agent"],
      "antibiotics_surgical": ["Safe option"],
      "antiemetics": ["Safe options"],
      "bp_management": ["Safe options"]
    }},
    "drugs_to_avoid": [
      {{"drug": "Drug name", "reason": "Specific reason from allergy data", "safe_alternative": "Alternative"}}
    ],
    "allergy_data_gap_risk": "What risk exists if allergy data is incomplete or not recorded",
    "allergy_safety_flags": ["Any specific flag based on actual allergy data"]
  }},
  "blood_group_management": {{
    "blood_group": "{blood_group}",
    "data_available": true,
    "compatible_donor_types": ["List based on actual blood group"],
    "emergency_uncrossmatched_sequence": "O- first if not recorded, else specific sequence for {blood_group}",
    "blood_products_likely_needed": true,
    "mtp_trigger_criteria_met": true,
    "mtp_trigger_rationale": "Based on injury data from DB",
    "blood_bank_preparation": {{
      "packed_rbc_units": "Units needed based on injury severity",
      "ffp_units": "Units at appropriate ratio",
      "platelets": "If indicated",
      "cryoprecipitate": "If indicated",
      "crossmatch": "STAT type and screen"
    }},
    "cross_match_required": true
  }},
  "surgical_history_flags": {{
    "previous_surgeries": "{prev_surgeries}",
    "surgery_type": "{surgery_type}",
    "implants_or_hardware": false,
    "mri_contraindication": false,
    "impact_on_current_care": "Specific impact from actual surgical history",
    "anaesthetic_history_note": "Based on what is/isn't recorded"
  }},
  "family_history_risk": {{
    "family_history_recorded": "{family_history}",
    "relevant_predispositions": ["Based on actual family history entries"],
    "cardiac_monitoring_additions": ["Specific monitoring additions from family history"],
    "ascvd_risk_comment": "Based on actual age/gender/family history",
    "risk_elevation": "None|Low|Moderate|High"
  }},
  "pregnancy_status": {{
    "status": "{pregnancy_status}",
    "treatment_modifications": "Modifications based on actual status",
    "restricted_drugs_if_applicable": []
  }},
  "treating_team_briefing_card": [
    "Bullet 1 with actual DB value — generated by LLM from actual data",
    "Bullet 2",
    "Bullet 3",
    "Bullet 4",
    "Bullet 5",
    "Bullet 6",
    "Bullet 7",
    "Bullet 8"
  ],
  "patient_safety_score": 0.0,
  "safety_score_breakdown": {{
    "medication_risk_score": 0.0,
    "medication_risk_notes": "Specific note on medications recorded",
    "allergy_risk_score": 0.0,
    "allergy_risk_notes": "Specific note on allergy data",
    "history_risk_score": 0.0,
    "history_risk_notes": "Specific note on surgical/family history",
    "composite": 0.0,
    "interpretation": "What this score means for this patient"
  }},
  "critical_flags_count": 0,
  "memory_completeness": 0.0,
  "load_percentage": 0
}}
"""
        result = await self._invoke(system, prompt)
        elapsed = self._elapsed(t0)
        logger.info(f"{self.agent_id} · MemoryIntakeAgent — DONE ({elapsed}ms)")
        
        # Check if result is just raw_output (meaning parse failed)
        if "raw_output" in result and len(result) == 1:
            deeper_parse = parse_llm_json(result["raw_output"])
            if "raw_output" not in deeper_parse:
                result = deeper_parse
                
        return {"memory_result": result, "timing": elapsed}


# ============================================================
# PARALLEL RUNNER
# ============================================================

async def run_all_intake_agents(state: IntakeAgentState) -> IntakeAgentState:
    logger.info("Parallel intake agent layer (PA1–PA3) — START")
    t0 = datetime.now().timestamp()

    pa1 = ClinicalIntakeAgent(llm)
    pa2 = InsuranceIntakeAgent(llm)
    pa3 = MemoryIntakeAgent(llm)

    results = await asyncio.gather(
        pa1.run(dict(state)),
        pa2.run(dict(state)),
        pa3.run(dict(state)),
        return_exceptions=True,
    )

    agent_keys  = ["PA1", "PA2", "PA3"]
    result_keys = ["clinical_result", "insurance_result", "memory_result"]

    for i, (result, rkey, akey) in enumerate(zip(results, result_keys, agent_keys)):
        if isinstance(result, Exception):
            logger.error(f"{akey} failed: {result}")
            state["errors"].append(f"{akey}: {str(result)}")
        else:
            state[rkey] = result.get(rkey, {})
            state["agent_timings"][akey] = result.get("timing", 0)

    elapsed = round((datetime.now().timestamp() - t0) * 1000, 1)
    logger.info(f"Parallel intake agent layer — DONE ({elapsed}ms)")
    return state


# ============================================================
# PS · SYNTHESIS AGENT — cross-agent conflict detection + deep merge
# ============================================================

class IntakeSynthesisAgent(BaseIntakeAgent):
    agent_id = "PS"

    async def run(self, state: IntakeAgentState) -> IntakeAgentState:
        logger.info(f"{self.agent_id} · IntakeSynthesisAgent — START")
        t0 = datetime.now().timestamp()

        patient = state.get("patient_record", {})
        intake  = state.get("intake_record", {})

        def safe_json(data):
            try:
                return json.dumps(data or {}, indent=2, default=str)
            except Exception:
                return '{"error": "Could not serialize result"}'

        # Helper to extract from raw_output if needed
        def clean_agent_result(data):
            if isinstance(data, dict) and "raw_output" in data and len(data) == 1:
                return parse_llm_json(data["raw_output"])
            return data or {}
        
        clinical_clean = clean_agent_result(state.get("clinical_result"))
        insurance_clean = clean_agent_result(state.get("insurance_result"))
        memory_clean = clean_agent_result(state.get("memory_result"))
        
        clinical_json = safe_json(clinical_clean)
        insurance_json = safe_json(insurance_clean)
        memory_json = safe_json(memory_clean)

        system = (
            "You are the synthesis intelligence for an emergency hospital intake system. "
            "You receive REAL outputs from 3 specialist agents. "
            "Merge them into a unified, clinically actionable dashboard. "
            "Detect actual conflicts between agents — cite the agent name and the specific conflicting fields. "
            "Resolve conflicts with clinical reasoning based on the actual data. "
            "Write every JSON string field as a specific sentence — never a generic label. "
            "Respond ONLY with valid JSON. No markdown, no preamble."
        )

        prompt = f"""
You are the SYNTHESIS AGENT (PS). Merge 3 specialist agent outputs into a unified hospital dashboard.
Base all synthesis on actual content of the agent outputs below. Detect real conflicts. Rank actions.

════════════════════════════════════════════════════
PATIENT CONTEXT (from DB)
════════════════════════════════════════════════════
Patient ID       : {sv(state["patient_id"])}
Assessment ID    : {sv(state["assessment_id"])}
Name             : {sv(patient.get("fullName", patient.get("name")))}
Age / Gender     : {sv(patient.get("age"))} / {sv(patient.get("gender"))}
Assessment Time  : {sv(intake.get("assessment_date"))} {sv(intake.get("assessment_time"), "")}
Accident         : {sv(patient.get("accidentDetails", {}).get("accidentType"))} at {sv(patient.get("accidentDetails", {}).get("location"))}

════════════════════════════════════════════════════
PA1 — CLINICAL AGENT OUTPUT
════════════════════════════════════════════════════
{clinical_json}

════════════════════════════════════════════════════
PA2 — INSURANCE AGENT OUTPUT
════════════════════════════════════════════════════
{insurance_json}

════════════════════════════════════════════════════
PA3 — MEMORY AGENT OUTPUT
════════════════════════════════════════════════════
{memory_json}

════════════════════════════════════════════════════
SYNTHESIS TASKS
════════════════════════════════════════════════════

TASK 1 — UNIFIED STATUS LINE
  One sentence: "Patient [name] | [age]/[gender] | Triage [level] | [emergency type] | [insurance badge]"
  Use actual values from agent outputs above.

TASK 2 — CRITICAL ACTION CHECKLIST (Top 8, ranked by urgency)
  For each: what action (cite actual drug/equipment from agent output), who does it,
  timeframe, which agent identified it, consequence of delay.

TASK 3 — CROSS-AGENT CONFLICT DETECTION
  Find real conflicts or gaps between PA1, PA2, PA3.
  Examples to check:
  - Does PA1 plan vasopressors? Does PA3 note a drug interaction with the patient's current medication that affects vasopressor response?
  - Does PA3 flag a BP target modification from chronic conditions? Does PA1 use the same target?
  - Does PA2 cashless status affect resource allocation noted in PA1?
  - Any drug PA1 plans that is flagged by PA3 allergy analysis?
  Resolve each conflict.

TASK 4 — INTEGRATED RISK SUMMARY (Top 5)
  Cross-agent risks where one agent's finding magnifies another's.
  Must name specific drugs/conditions/values from the actual agent outputs.

TASK 5 — DUTY DOCTOR NARRATIVE (5 sentences)
  Written for a doctor picking up this case in 30 seconds.
  Must reference actual values: patient name, age, mechanism from DB,
  current clinical state, top action, insurance status, key drug warning from PA3.

TASK 6 — COMPOSITE CONFIDENCE
  Weighted: clinical (0.4) + insurance (0.3) + memory (0.3)
  Use actual data completeness from each agent's output.

Return ONLY valid JSON:
{{
  "agent": "PS-SynthesisAgent",
  "patient_id": "{sv(state["patient_id"])}",
  "assessment_id": "{sv(state["assessment_id"])}",
  "timestamp": "{datetime.now().isoformat()}",
  "unified_status": {{
    "status_line": "Patient [name] | [age]/[gender] | Triage [level] | [type] | [insurance]",
    "triage_level": "RED|ORANGE|YELLOW|GREEN",
    "emergency_type": "Derived from PA1 output",
    "severity": "CRITICAL|SERIOUS|MODERATE|MINOR",
    "insurance_status": "Derived from PA2 output",
    "primary_action_now": "Specific action from PA1 or PA3 with responsible person"
  }},
  "critical_action_checklist": [
    {{
      "rank": 1,
      "action": "Specific action with drug/dose/equipment from agent output",
      "responsible": "Named clinical role",
      "timeframe": "Within X minutes",
      "source_agent": "PA1|PA2|PA3",
      "consequence_if_delayed": "Specific consequence from clinical data"
    }}
  ],
  "cross_agent_conflicts": [
    {{
      "conflict_id": 1,
      "conflict": "Specific disagreement or gap between agents — cite field names",
      "agents_involved": ["PA1", "PA3"],
      "resolution": "Specific resolved guidance",
      "basis": "Clinical/pharmacological reasoning from actual data"
    }}
  ],
  "integrated_risk_summary": [
    {{
      "rank": 1,
      "risk": "Cross-agent risk with named drugs/conditions from actual agent outputs",
      "source_agents": ["PA1", "PA3"],
      "severity": "Critical|High|Moderate",
      "combined_effect": "Why these together are worse than individually",
      "mitigation": "Specific mitigation with actual drug/action name"
    }}
  ],
  "dashboard_narrative": "5-sentence duty doctor narrative referencing actual patient name, mechanism, values, action, and drug warning from PA3",
  "composite_confidence": 0.0,
  "confidence_calculation": "0.4×PA1(score) + 0.3×PA2(score) + 0.3×PA3(score) = total",
  "agent_confidence_breakdown": {{
    "PA1_clinical": 0.0,
    "PA2_insurance": 0.0,
    "PA3_memory": 0.0
  }},
  "hospital_dashboard_card": {{
    "triage_badge": "🔴 CRITICAL|🟠 URGENT|🟡 DELAYED|🟢 MINOR",
    "clinical_alert": "Specific alert with actual values from PA1",
    "memory_note": "Key drug warning from PA3 using actual medication from DB",
    "insurance_badge": "✅ CASHLESS APPROVED|⚠️ VERIFY MANUALLY|❌ NO INSURANCE",
    "top_action": "Single most urgent action with named responsible person",
    "drug_warning": "Most critical drug interaction or contraindication from PA3 using actual drug name"
  }}
}}
"""
        state["synthesis_result"] = await self._invoke(system, prompt)
        state["agent_timings"][self.agent_id] = self._elapsed(t0)
        logger.info(
            f"{self.agent_id} · IntakeSynthesisAgent — DONE "
            f"({state['agent_timings'][self.agent_id]}ms)"
        )
        return state


# ============================================================
# FULL PIPELINE RUNNER
# ============================================================

async def run_intake_pipeline(
    patient_id: str,
    assessment_id: Optional[str] = None
) -> IntakeAgentState:

    intake_record, patient_record = await asyncio.gather(
        fetch_latest_intake(patient_id, assessment_id),
        fetch_patient_base(patient_id),
    )

    if not intake_record:
        raise HTTPException(
            status_code=404,
            detail=f"No intake assessment found for patient_id: {patient_id}"
        )

    resolved_assessment_id = intake_record.get("assessment_id", str(uuid.uuid4()))

    state: IntakeAgentState = {
        "patient_id":       patient_id,
        "assessment_id":    resolved_assessment_id,
        "intake_record":    intake_record,
        "patient_record":   patient_record,
        "clinical_result":  None,
        "insurance_result": None,
        "memory_result":    None,
        "synthesis_result": None,
        "errors":           [],
        "agent_timings":    {},
    }

    state = await run_all_intake_agents(state)

    synthesis_agent = IntakeSynthesisAgent(llm_synthesis)
    state = await synthesis_agent.run(state)

    return state


# ============================================================
# API ENDPOINTS
# ============================================================

@router.post("/patient-intake/analyze")
async def analyze_patient_intake(request: IntakeAgentRequest):
    """
    Run 3-agent parallel deep analysis on a submitted patient intake assessment.

    v3.0.0:
      - Fully dynamic: all agent prompts derive 100% from DB records.
      - max_tokens increased to prevent truncated JSON (raw_output).
      - Robust JSON parser handles partial/truncated responses.
      - Pre-computation helpers (shock index, MAP, GCS, cost estimates) are data-driven.
      - Medication timing computed from actual last-dose timestamp, not hardcoded.
    """
    start_ms = datetime.now().timestamp() * 1000
    logger.info(f"Intake agent pipeline v3 | patient={request.patient_id}")

    try:
        state = await run_intake_pipeline(
            patient_id=request.patient_id,
            assessment_id=request.assessment_id,
        )

        elapsed = round(datetime.now().timestamp() * 1000 - start_ms)

        try:
            save_doc = {
                "patient_id":         request.patient_id,
                "assessment_id":      state["assessment_id"],
                "processed_at":       datetime.utcnow(),
                "processing_time_ms": elapsed,
                "clinical_result":    state.get("clinical_result"),
                "insurance_result":   state.get("insurance_result"),
                "memory_result":      state.get("memory_result"),
                "synthesis_result":   state.get("synthesis_result"),
                "errors":             state.get("errors", []),
                "agent_timings":      state.get("agent_timings", {}),
                "version":            "3.0.0",
            }
            await agent_results_collection.insert_one(save_doc)
        except Exception as db_err:
            logger.error(f"MongoDB agent result save failed: {db_err}")

        response = {
            "patient_id":          request.patient_id,
            "assessment_id":       state["assessment_id"],
            "processed_at":        datetime.now().isoformat(),
            "processing_time_ms":  elapsed,
            "version":             "3.0.0",
            "agent_timings":       state.get("agent_timings", {}),
            "errors":              state.get("errors", []),

            "triage_level":        (state.get("synthesis_result") or {}).get("unified_status", {}).get("triage_level", ""),
            "severity":            (state.get("synthesis_result") or {}).get("unified_status", {}).get("severity", ""),
            "emergency_type":      (state.get("synthesis_result") or {}).get("unified_status", {}).get("emergency_type", ""),
            "primary_action_now":  (state.get("synthesis_result") or {}).get("unified_status", {}).get("primary_action_now", ""),
            "dashboard_narrative": (state.get("synthesis_result") or {}).get("dashboard_narrative", ""),
            "composite_confidence":(state.get("synthesis_result") or {}).get("composite_confidence", 0),
            "hospital_dashboard_card": (state.get("synthesis_result") or {}).get("hospital_dashboard_card", {}),

            "clinical_result":    state.get("clinical_result"),
            "insurance_result":   state.get("insurance_result"),
            "memory_result":      state.get("memory_result"),
            "synthesis_result":   state.get("synthesis_result"),
        }

        logger.info(
            f"Intake pipeline v3 complete | patient={request.patient_id} | "
            f"{elapsed}ms | triage={response['triage_level']}"
        )
        return response

    except HTTPException:
        raise
    except Exception as e:
        logger.exception(f"Intake pipeline failed | patient={request.patient_id} | {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/patient-intake/analyze/{patient_id}")
async def analyze_patient_intake_get(
    patient_id: str,
    assessment_id: Optional[str] = None
):
    request = IntakeAgentRequest(patient_id=patient_id, assessment_id=assessment_id)
    return await analyze_patient_intake(request)


@router.get("/patient-intake/analyze/latest/{patient_id}")
async def get_latest_patient_analysis(patient_id: str):
    """Fetch the LATEST agent analysis for a patient."""
    try:
        cursor = agent_results_collection.find(
            {"patient_id": patient_id},
            {"_id": 0}
        ).sort("processed_at", -1).limit(1)

        results = await cursor.to_list(length=1)

        if not results:
            return {
                "status": "not_found",
                "patient_id": patient_id,
                "message": "No agent results found. Run POST /patient-intake/analyze first.",
            }

        result   = results[0]
        synthesis = result.get("synthesis_result", {})
        unified_status = synthesis.get("unified_status", {})

        return {
            "status":               "success",
            "version":              result.get("version", "1.0.0"),
            "patient_id":           patient_id,
            "assessment_id":        result.get("assessment_id"),
            "processed_at":         result.get("processed_at"),
            "processing_time_ms":   result.get("processing_time_ms", 0),
            "triage_level":         unified_status.get("triage_level", ""),
            "severity":             unified_status.get("severity", ""),
            "emergency_type":       unified_status.get("emergency_type", ""),
            "primary_action_now":   unified_status.get("primary_action_now", ""),
            "dashboard_narrative":  synthesis.get("dashboard_narrative", ""),
            "composite_confidence": synthesis.get("composite_confidence", 0),
            "hospital_dashboard_card": synthesis.get("hospital_dashboard_card", {}),
            "clinical_result":      result.get("clinical_result"),
            "insurance_result":     result.get("insurance_result"),
            "memory_result":        result.get("memory_result"),
            "synthesis_result":     result.get("synthesis_result"),
            "agent_timings":        result.get("agent_timings", {}),
            "errors":               result.get("errors", []),
        }

    except Exception as e:
        logger.exception(f"Error fetching latest analysis for {patient_id}: {e}")
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/patient-intake/agent-results/{patient_id}")
async def get_agent_results(patient_id: str):
    try:
        cursor = agent_results_collection.find(
            {"patient_id": patient_id}, {"_id": 0}
        ).sort("processed_at", -1).limit(5)
        results = await cursor.to_list(length=5)
        if not results:
            raise HTTPException(status_code=404, detail=f"No agent results found for patient_id: {patient_id}")
        return {"status": "success", "patient_id": patient_id, "results": results, "count": len(results)}
    except HTTPException:
        raise
    except Exception as e:
        raise HTTPException(status_code=500, detail=str(e))


@router.get("/patient-intake/agents/health")
async def agents_health():
    return {
        "status":   "ok",
        "version":  "3.0.0",
        "agents":   4,
        "pipeline": [
            "PA1 · Clinical Agent  — Fully dynamic: Shock Index, MAP, RTS, ATLS, imaging orders [PARALLEL]",
            "PA2 · Insurance Agent — Fully dynamic: per-service cost analysis, shortfall calc, cashless protocol [PARALLEL]",
            "PA3 · Memory Agent    — Fully dynamic: drug interactions from actual meds, blood group MTP, allergy safety [PARALLEL]",
            "PS  · Synthesis Agent — Cross-agent conflict detection + integrated risk summary",
        ],
        "llm_fast":      "llama-3.1-8b-instant  (PA1, PA2, PA3) — 8000 tokens",
        "llm_synthesis": "llama-3.3-70b-versatile (PS) — 10000 tokens",
        "parallel_execution": True,
        "dynamic_features": [
            "All prompts built 100% from DB records — no hardcoded patient data",
            "Shock Index and MAP computed from actual vitals",
            "GCS classification from actual neuro sub-scores",
            "Medication timing from actual last-dose timestamp",
            "Treatment cost estimates based on actual accident/injury type",
            "Coverage shortfall from actual policy limit vs dynamic cost estimate",
            "Drug interactions analyzed for actual medication in DB",
            "Blood group compatibility from actual recorded blood group",
        ],
        "json_parsing": "Robust — handles truncated JSON, markdown fences, leading text",
        "data_sources": [
            "patient_intake_assessments — intake form data",
            "patients                   — base patient demographics",
        ],
        "output_collection": "intake_agent_results",
    }


# ============================================================
# FastAPI App (standalone)
# ============================================================

if __name__ == "__main__":
    from fastapi import FastAPI
    import uvicorn

    app = FastAPI(
        title="Patient Intake Agent API",
        description="3-Agent parallel deep analysis system for emergency patient intake v3.0.0",
        version="3.0.0",
    )
    app.include_router(router, prefix="/api/hms/users/data/context")
    uvicorn.run(app, host="0.0.0.0", port=8002, log_level="info")