"""
patient_app/routes_doctor.py  (REWRITTEN)

Doctor-facing endpoints, reached only through the gateway proxy
(X-Doctor-Id injected). New: photos (patient-CONFIRMED version only) with
an image-streaming endpoint, follow-up Q&A, typed answers, compare answers.
"""

from datetime import datetime, timedelta, timezone
from typing import Optional

from bson import ObjectId
from bson.errors import InvalidId
from fastapi import APIRouter, Depends, HTTPException, Query, Request, Response
from pydantic import BaseModel, Field

from .auth import Doctor, get_current_doctor
from .config import MAX_BODY_BYTES, TZ
from .db import patient_alerts, patient_checkin_photos, patient_checkins, patient_messages
from .services import care_data, medications as medications_svc
from .services import doctor_overview as overview_svc
from .services import photos as photos_svc

_DEFAULT_WINDOW_DAYS = 14
_MAX_WINDOW_DAYS = 90
_COMPARE_LABELS = ["Gone", "Better", "About the same", "Worse"]


async def guard(request: Request, response: Response) -> None:
    length = request.headers.get("content-length")
    if length and length.isdigit() and int(length) > MAX_BODY_BYTES:
        raise HTTPException(status_code=413, detail="Request too large")
    response.headers["Cache-Control"] = "no-store"


router = APIRouter(prefix="/patient_app/doctor", tags=["patient_app_doctor"], dependencies=[Depends(guard)])


async def _require_association(doctor: Doctor, patient_id: str) -> None:
    if doctor.sys_user_id not in await care_data.get_patient_doctor_ids(patient_id):
        raise HTTPException(status_code=403, detail="Not associated with this patient")


@router.get("/patients/{patient_id}/overview")
async def get_patient_overview(
    patient_id: str,
    doctor: Doctor = Depends(get_current_doctor),
    days: int = Query(default=_DEFAULT_WINDOW_DAYS, ge=1, le=_MAX_WINDOW_DAYS),
):
    await _require_association(doctor, patient_id)
    now = datetime.now(timezone.utc)
    today_local = now.astimezone(TZ).date()
    since_date = (today_local - timedelta(days=days - 1)).isoformat()
    local_date = today_local.isoformat()

    med_docs = await care_data.load_med_docs(patient_id)
    current = medications_svc.select_current_docs(med_docs)
    med_doctor_names = await care_data.get_doctor_names(list(current.keys()))
    statuses = await care_data.load_slot_statuses(patient_id, local_date)
    medications_payload = medications_svc.build_medications(current, med_doctor_names, statuses, now, TZ)

    checkin_docs = await care_data.load_recent_checkins(patient_id, limit=days)
    checkin_docs = [c for c in checkin_docs if (c.get("date") or "") >= since_date]
    alert_docs = await care_data.load_alerts(patient_id)
    med_log_rows = await care_data.load_med_log_window(patient_id, since_date)
    return overview_svc.build_overview(
        medications_payload=medications_payload, checkin_docs=checkin_docs, alert_docs=alert_docs,
        med_log_rows=med_log_rows, days=days, today=today_local,
    )


def _pretty(qid: str) -> str:
    return qid.replace("_", " ").replace("-", " ").capitalize()


def _fmt(kind: Optional[str], v) -> str:
    if v is None:
        return "not answered"
    if kind == "yesno":
        return "Yes" if v == 1 else "No"
    if kind == "compare":
        try:
            return _COMPARE_LABELS[int(v)]
        except (ValueError, IndexError):
            return str(v)
    if kind in ("bother", "body"):
        return f"{v}/4"
    return str(v)


def _photo_view(p: dict) -> dict:
    """Patient-CONFIRMED version only; English preferred for the doctor."""
    c = p.get("confirmed") or {}
    return {
        "photo_id": p.get("photo_id"),
        "category": c.get("category"),
        "items": c.get("items_en") or c.get("items_local") or [],
        "note": c.get("note_en") or c.get("note"),
        "at": p["sent_at"].isoformat() if p.get("sent_at") else None,
    }


async def _photos_map(patient_id: str, ids: list) -> dict:
    if not ids:
        return {}
    cur = patient_checkin_photos.find(
        {"patient_id": patient_id, "photo_id": {"$in": ids}, "sent": True},
        {"_id": 0, "photo_id": 1, "confirmed": 1, "sent_at": 1},
    )
    return {p["photo_id"]: _photo_view(p) async for p in cur}


def _build_day(c: dict, photos: dict) -> dict:
    """Rule-based daily summary: nothing here is generated by an LLM."""
    questions = [q for q in (c.get("questions") or []) if isinstance(q, dict) and q.get("id")]
    sym = c.get("symptoms") or {}
    ft = c.get("free_text_answers") or {}
    qmap = {q["id"]: q for q in questions}
    ids = [q["id"] for q in questions] + [k for k in sym if k not in qmap]

    items, problems, urgent = [], [], []
    for qid in ids:
        q = qmap.get(qid, {})
        kind = q.get("kind")
        v = sym.get(qid)
        label = q.get("label") or _pretty(qid)
        isnum = isinstance(v, (int, float))
        if kind == "yesno":
            is_problem = v == 1
        elif kind == "compare":
            is_problem = isnum and v >= 2  # about the same / worse
        else:
            is_problem = isnum and v >= 1
        is_urgent = bool(is_problem and (
            (q.get("urgent") and (kind != "compare" or v == 3))
            or (isnum and kind in ("bother", "body") and v >= 3)))
        if is_problem:
            problems.append(label)
        if is_urgent:
            urgent.append(label)
        items.append({"id": qid, "label": label, "group": q.get("group"), "kind": kind,
                      "answer": _fmt(kind, v), "problem": bool(is_problem), "urgent": is_urgent,
                      "typed": ft.get(qid)})

    parts = []
    if c.get("weight") is not None:
        parts.append(f"Weight {c['weight']} kg")
    if c.get("red_flag"):
        parts.append("RED FLAG reported")
    parts.append(f"{len(problems)} of {len(items)} answered Yes/problem" if items else "no question answers saved")
    if problems:
        parts.append("Problems: " + ", ".join(problems[:8]) + ("…" if len(problems) > 8 else ""))
    if urgent:
        parts.append("URGENT: " + ", ".join(urgent))
    if c.get("note"):
        parts.append("Note: " + c["note"][:120])
    day_photos = [photos[i] for i in (c.get("photo_ids") or []) if i in photos]
    if day_photos:
        parts.append(f"{len(day_photos)} photo(s)")
    return {
        "date": c.get("date"), "weight": c.get("weight"), "red_flag": bool(c.get("red_flag")),
        "summary": " · ".join(parts), "items": items, "note": c.get("note") or "",
        "body_sites": c.get("body_sites"), "follow_up": c.get("follow_up"),
        "followups": c.get("followups") or [], "photos": day_photos,
        "food_items": c.get("food_items"), "questions_saved": bool(questions),
        "submitted_at": c.get("submitted_at"),
    }


@router.get("/patients/{patient_id}/timeline")
async def get_patient_timeline(
    patient_id: str,
    doctor: Doctor = Depends(get_current_doctor),
    days: int = Query(default=_DEFAULT_WINDOW_DAYS, ge=1, le=_MAX_WINDOW_DAYS),
):
    await _require_association(doctor, patient_id)
    since = (datetime.now(TZ).date() - timedelta(days=days - 1)).isoformat()
    cur = patient_checkins.find({"patient_id": patient_id, "date": {"$gte": since}}, {"_id": 0}).sort("date", -1)
    checkins = await cur.to_list(length=days * 3)

    mcur = patient_messages.find({"patient_id": patient_id, "kind": {"$ne": "checkin"}}).sort("created_at", -1)
    msgs = await mcur.to_list(length=150)

    photo_ids = [i for c in checkins for i in (c.get("photo_ids") or [])]
    photo_ids += [m["photo_id"] for m in msgs if m.get("kind") == "photo" and m.get("photo_id")]
    photos = await _photos_map(patient_id, list(set(photo_ids)))

    out_msgs = []
    for m in msgs:
        kind = m.get("kind", "text")
        item = {
            "id": str(m["_id"]), "from": m.get("from", "patient"), "kind": kind, "text": m.get("text", ""),
            "doctor_name": m.get("doctor_name"), "urgent": bool(m.get("urgent")),
            "at": m["created_at"].isoformat() if m.get("created_at") else None,
        }
        if kind == "photo":
            if m.get("photo_id") not in photos:
                continue
            item["photo"] = photos[m["photo_id"]]
        elif kind == "followup":
            item["qa"] = m.get("qa") or []
        out_msgs.append(item)

    return {"status": "success", "days": [_build_day(c, photos) for c in checkins], "messages": out_msgs}


@router.get("/patients/{patient_id}/photos/{photo_id}/image")
async def get_photo_image(patient_id: str, photo_id: str, doctor: Doctor = Depends(get_current_doctor)):
    await _require_association(doctor, patient_id)
    doc = await patient_checkin_photos.find_one(
        {"patient_id": patient_id, "photo_id": photo_id, "sent": True}, {"photo_url": 1})
    if not doc:
        raise HTTPException(status_code=404, detail="Photo not found")
    data = await photos_svc.fetch_image(doc)
    if not data:
        raise HTTPException(status_code=404, detail="Image not available")
    return Response(content=data[0], media_type=data[1], headers={"Cache-Control": "private, max-age=600"})


class DoctorMessageIn(BaseModel):
    text: str = Field(..., min_length=1, max_length=1000)


@router.post("/patients/{patient_id}/messages")
async def send_doctor_message(patient_id: str, payload: DoctorMessageIn, doctor: Doctor = Depends(get_current_doctor)):
    await _require_association(doctor, patient_id)
    names = await care_data.get_doctor_names([doctor.sys_user_id])
    name = (names.get(doctor.sys_user_id) or {}).get("name")
    now = datetime.now(timezone.utc)
    res = await patient_messages.insert_one({
        "patient_id": patient_id, "from": "doctor", "kind": "text", "doctor_id": doctor.sys_user_id,
        "doctor_name": name, "text": payload.text.strip(), "created_at": now,
    })
    return {"status": "success", "message": {
        "id": str(res.inserted_id), "from": "doctor", "kind": "text", "text": payload.text.strip(),
        "doctor_name": name, "urgent": False, "at": now.isoformat()}}


@router.post("/alerts/{alert_id}/acknowledge")
async def acknowledge_alert(alert_id: str, doctor: Doctor = Depends(get_current_doctor)):
    try:
        oid = ObjectId(alert_id)
    except InvalidId:
        raise HTTPException(status_code=404, detail="Alert not found")
    existing = await patient_alerts.find_one({"_id": oid}, {"patient_id": 1})
    if not existing:
        raise HTTPException(status_code=404, detail="Alert not found")
    await _require_association(doctor, existing["patient_id"])
    await patient_alerts.update_one(
        {"_id": oid},
        {"$set": {"acknowledged": True, "acknowledged_by": doctor.sys_user_id,
                  "acknowledged_at": datetime.now(timezone.utc)}},
    )
    return {"status": "success", "id": alert_id}